### ISSUE TITLE
model in hugging face cannot download

### ISSUE THREAD

**Issue by leavenotrace** [Huanshere/VideoLingo#10]
[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: pip3.11 install --upgrade pip
Downloading UVR model...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

**Comment by leavenotrace** [comment]
def dowanload_uvr_model():
    """Download the specified uvr model."""
    if not os.path.exists("_model_cache/uvr5_weights/HP2_all_vocals.pth"):
        os.makedirs("_model_cache/uvr5_weights", exist_ok=True)
        import requests
        print("Downloading UVR model...")
        url = "https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/e992cb1bc5d777fcddce20735a899219b1d46aba/uvr5_weights/HP2_all_vocals.pth"
        response = requests.get(url)
        with open("_model_cache/uvr5_weights/HP2_all_vocals.pth", "wb") as file:
            file.write(response.content)
        print("UVR model downloaded successfully.")
    else:
        print("HP2_all_vocals.pth already exists. Skipping download.")

**Comment by leavenotrace** [comment]
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/95daba30-2e7b-435d-8b76-e59180923b87">

**Comment by Huanshere** [comment]
That huggingface url link should lead you directly to download the model. 

Seems like you should consider connecting to a VPN.

**Comment by leavenotrace** [comment]
Those files cannot download too. can you put it another path?

def download_huanyu_model():
    """Download the specified Huanyu model files for GPT-SoVITS."""
    base_url = "https://huggingface.co/Huan69/GPT-SoVITS-Huanyu/resolve/main/"
    model_dir = os.path.join("_model_cache", "GPT_SoVITS", "trained", "Huanyu")
    os.makedirs(model_dir, exist_ok=True)

    files = [
        "huanyushort222-e10.ckpt",
        "huanyushort222_e15_s135.pth",
        "infer_config.json",
        "and to be able to get really good results doing that for a variety of classes.wav"
    ]

    for file in files:
        save_path = os.path.join(model_dir, file)
        if os.path.exists(save_path):
            print(f"{file} already exists. Skipping download.")
            continue

        url = base_url + file
        if file == "and to be able to get really good results doing that for a variety of classes.wav":
            url = base_url + "and%20to%20be%20able%20to%20get%20really%20good%20results%20doing%20that%20for%20a%20variety%20of%20classes.wav"
        import requests
        print(f"Downloading {file}...")
        response = requests.get(url)
        if response.status_code == 200:
            with open(save_path, "wb") as f:
                f.write(response.content)
            print(f"{file} downloaded successfully.")
        else:
            print(f"Failed to download {file}, status code: {response.status_code}")

**Comment by Huanshere** [comment]
Which cloud storage service do you prefer? I'm glad to share all the files.

**Comment by leavenotrace** [comment]
aliyun

**Comment by Huanshere** [comment]
Sorry I am in Canada right now and cannot access to Aliyun, but I can provide Baidu cloud storage link as follows:"https://pan.baidu.com/s/1KuIvDmZn0mWPEEaDn65bkg?pwd=mjpt"
