### ISSUE TITLE
本地wishper能否切换成最新发布的whisper-large-v3-turbo

### ISSUE THREAD

**Issue by vanch007** [Huanshere/VideoLingo#101]
https://huggingface.co/openai/whisper-large-v3-turbo
Whisper large-v3-turbo 是对精简版 Whisper large-v3 进行微调的版本。换句话说，它与原始模型完全相同，只是解码层的数量从 32 层减少到 4 层。因此，模型的速度大大提高，但质量略有下降。

**Comment by Huanshere** [comment]
VideoLingo 的转录使用的是 whisperX 项目，以质量为第一考量，whisper turbo 据报道是有精度下降的。

另外，从速度来说，faster whisper 比 whisper 快了四倍，turbo 快八倍，相比之下应该没有太大的区别，所以暂不考虑～
