### ISSUE TITLE
请问能否增加一个不添加BaseURL后缀的选项，来兼容更多的模型API地址？

### ISSUE THREAD

**Issue by Rakshesha2024** [Huanshere/VideoLingo#103]
想测试一下其他的模型，但有的API地址和OpenAI的地址格式有所不同，如智谱AI。
请问能否增加一个选项，自定义是否开启BaseURL的/V1后缀，以此兼容更多的模型调用

**Comment by Huanshere** [comment]
感谢建议～

考虑到两点：
- 经过广泛测试，只有 sonnet 能够稳定不报错，其余大部分模型包括 gemini pro 都小概率出现没有遵循 json 格式的报错
- 为单独接口做适配会增加代码和页面复杂度

因此建议使用oneapi 搭建统一接口，或者使用中转站（例如 OHMYGPT）进行其他模型的测试～
