### ISSUE TITLE
只需要翻译中文字幕会考虑支持本地LLM模型吗？

### ISSUE THREAD

**Issue by DreamLoveBetty** [Huanshere/VideoLingo#106]

**Comment by Huanshere** [comment]
会考虑，在下个版本会有只翻译字幕的小工具～

**Comment by msn1983aa** [comment]
> 会考虑，在下个版本会有只翻译字幕的小工具～

很需要，感谢感谢！期待更新

**Comment by DreamLoveBetty** [comment]
很期待，谢谢

**Comment by lonrencn** [comment]
现在已经可以使用本地模型了，但是你的模型要足够聪明，qwen2:7b 目前测试不太行，2.5：32b 还可以，不然会报N多错误。
另外，在使用本地模型时，要在config文件里把并发工人，默认的8改成你自己设置的数。

**Comment by dark00-cn** [comment]
> 现在已经可以使用本地模型了，但是你的模型要足够聪明，qwen2:7b 目前测试不太行，2.5：32b 还可以，不然会报N多错误。 另外，在使用本地模型时，要在config文件里把并发工人，默认的8改成你自己设置的数。

请问这个必须用CLAUD3.5么  我把链接改成本地https://127.0.0.1:11434的OLLAMA里的qwan2.5:14b 好像报了一堆错Exception: Still failed after 3 attempts: Connection error.

**Comment by Huanshere** [comment]
Connection error 是并发数太大，可以在 config 中调整并发数为 1。另外不建议使用别的模型，可能引起格式错误。
