### ISSUE TITLE
原声分离效果有点不太理想、视频分辨率低、中文语音转换后音量过低

### ISSUE THREAD

**Issue by neohob** [Huanshere/VideoLingo#11]
1. 原声分离后不明显还是能听清原声的音频（体育解说类）
2. 视频分辨率很低只有 480p，是否可以调整（原视频起码是有 1080p 的）
3. 转换到中文语音后，总音量很低，开大最大也很低，是否能调整

**Comment by Huanshere** [comment]
1. GPT-SoVits 官方训练流程推荐使用两阶段的人声分离处理，本项目仅仅简单采用了第一步（原以为足够用了）。感谢反馈，后续会加上。
2. 在 core/step7_xxx.py 中可以设置分辨率。默认使用较低分辨率是为了加快渲染速度，同时提供一个快速预览的demo版本。，提供 srt 给用户手动校对和压制。
3. 总音量低这个和我的底模有关(训练音频声音小)，可以考虑在剪辑软件中调整。虽然在代码层面也可以实现音量调节，但考虑到底模更换可能带来的频繁调整需求，这可能不是最优解。
