### ISSUE TITLE
whisperX转录德语，法语音频会跳掉一些很简单的句子不转录到字幕上

### ISSUE THREAD

**Issue by sijitang** [Huanshere/VideoLingo#111]
请问选本地或者在google lab选whisperX model时候是不是要额外设置一些参数

**Comment by Huanshere** [comment]
设置为auto即可，whisper会自动识别。可以尝试使用replicate的云端版本，看看问题是否会复现。whisperX的对齐字幕时间轴会采用专门的wav2vac模型，可能使用的非英语模型效果不够完美，或者由于bgm声音太大导致的对齐错误，会因为这几种情况漏词。但是另一个好处在于，这个方法能完全避免whisper本身的幻觉问题。

**Comment by yxc0915** [comment]
1.5.1版本已发，请检查新版本是否会出现同样的问题
