### ISSUE TITLE
whisper-large-v3-turbo 已经发布

### ISSUE THREAD

**Issue by SomeoneKong** [Huanshere/VideoLingo#113]
https://huggingface.co/openai/whisper-large-v3-turbo

**Comment by Huanshere** [comment]
用精度下降换取了更好的性能，但本项目追求更好的翻译质量，时间和性能上的要求不高，先观望一下~

**Comment by vanch007** [comment]
> 用精度下降换取了更好的性能，但本项目追求更好的翻译质量，时间和性能上的要求不高，先观望一下~

mac本地 whishperX 的速度很慢，mps 还不支持 fast-whisper，whisper-large-v3-turbo 在 mac 上可以用 mps 加速，四五十分钟的对话只要三分钟左右

**Comment by Huanshere** [comment]
本项目必须依赖于whisperX，只有它能提供稳定的单词级时间轴，所以 mac 暂时没法使用 mps 加速了
