### ISSUE TITLE
是否可以支持竖屏格式的视频

### ISSUE THREAD

**Issue by sofs2005** [Huanshere/VideoLingo#120]
我试了下竖屏会强制改成横屏，能不能保持原有视频比例进行输出呢？

**Comment by yxc0915** [comment]
最后的视频输出是ffmpeg的功能，可能不是很好改。如果你会使用剪映这些软件的话，可以试着把原视频和生成的字幕文件（.srt）一起导入进去，在里面可以调节更丰富的字幕样式。

**Comment by sofs2005** [comment]
> 最后的视频输出是ffmpeg的功能，可能不是很好改。如果你会使用剪映这些软件的话，可以试着把原视频和生成的字幕文件（.srt）一起导入进去，在里面可以调节更丰富的字幕样式。

好吧，暂时只能这样了

**Comment by Huanshere** [comment]
可以支持，但是单行字幕就会超出，建议还是自己压制~ 以后会考虑
