### ISSUE TITLE
 想问下批量支持断点续跑吗？

### ISSUE THREAD

**Issue by colin4k** [Huanshere/VideoLingo#126]
as title

**Comment by Huanshere** [comment]
仅仅支持任务级别的断电续跑（也就是一个任务跑完了就会记录 Done，断点跑从下一个开始），不支持单个任务的断点续跑（重跑会删掉现在的 output 重来）

**Comment by colin4k** [comment]
> 仅仅支持任务级别的断电续跑（也就是一个任务跑完了就会记录 Done，断点跑从下一个开始），不支持单个任务的断点续跑（重跑会删掉现在的 output 重来）

嗯，就是发现这个问题才问的，现在有个笨办法，就是把 batch 出错的 batch/output/error/里面具体出错文件的目录里面的内容复制到 output 目录，然后在 webui 里面就可以续跑这个文件的任务。所以这个过程感觉其实是可以自动化的。
