### ISSUE TITLE
可以直接输入youtube url吗？

### ISSUE THREAD

**Issue by mobilestack** [Huanshere/VideoLingo#13]
直接对这个视频进行操作

**Comment by mobilestack** [comment]
云上的项目不是最新版本的吗？只能上传本地视频

**Comment by Huanshere** [comment]
云机房在国内你懂的，自己部署挂了梯子就可以输入 ytb 链接下载🤓

**Comment by mobilestack** [comment]
等google colab支持python 3.12之后再试试，现在只支持3.10，放进去有不少地方要改。趋动云没跑通，本地电脑又没GPU。

**Comment by Huanshere** [comment]
诶 趋动云有什么问题吗

**Comment by Huanshere** [comment]
可以自己在 ssyoutube 之类的网站下载了然后上传上去

**Comment by mobilestack** [comment]
> 诶 趋动云有什么问题吗

当时是贴了一个太长的视频了，之后我换个短一些的再试试

**Comment by mobilestack** [comment]
> 可以自己在 ssyoutube 之类的网站下载了然后上传上去

是的，先本地yt-dlp就好

**Comment by mobilestack** [comment]
> 诶 趋动云有什么问题吗

贴了一个短一点的视频，在云上跑完了字幕翻译生成这一步。但是sovits配音这步还有点问题。

另外，第一次执行完提取音频和翻译后，顺手点了那个一键归档到history，结果需要重新再来一遍。感觉这个地方可以先不放这个按钮，等全部生肉烤熟了之后再操作这个。

配音那步，会报错
ParameterError: Audio buffer is not finite everywhere

接着再运行，会报错下面的

OSError: [Errno 30] Read-only file system: '/gemini/pretrain/_model_cache/GPT_SoVITS/trained/Huanyu/and to be able to get really good results doing that for a variety of classes.wav'

**Comment by Huanshere** [comment]
嗯云版本的还不支持配音，有点小代码要修改，新的云版本把配音暂时去掉了，后面会加上
