### ISSUE TITLE
建议增加一个提供srt文件的选项

### ISSUE THREAD

**Issue by rockets-cn** [Huanshere/VideoLingo#133]
有些原创的视频，字幕文件以经过处理，能确保内容的正确，不需要whisper的处理。
建议提供一个选项，供后续的操作。
该功能方便没有显卡的用户使用。

**Comment by Huanshere** [comment]
好的！会添加到开发路线里，感谢反馈！！！

**Comment by AlwaysBusyLzc** [comment]
我也需要这个功能

**Comment by mozz85** [comment]
能导出srt吗？可能需要对生成的字幕进行校验。

**Comment by Huanshere** [comment]
可以的 现在处理完会有下载字幕文件的选项，在 output 文件夹下也可以找到

> 能导出srt吗？可能需要对生成的字幕进行校验。

**Comment by shitou333111** [comment]
> 好的！会添加到开发路线里，感谢反馈！！！

基于已有字幕直接翻译确实是个很常用的功能，因为很多Youtube已经有校对过的英文字幕，不必再用whisper，能省下不少时间。但在另一个ISSUE里你又提到本项目基于whisper单词级别的时间戳来split, 基于已有字幕不在流程当中。所以还会加这个功能吗？

**Comment by xtremforce** [comment]
+10086 非常需要此功能
