### ISSUE TITLE
建议：增加单独的音轨以及使用单独的GPT-SoVITS service

### ISSUE THREAD

**Issue by jenningsloy318** [Huanshere/VideoLingo#134]
很棒的项目，通过这个项目翻译一些学习视频和动画片给小朋友，很有帮助
有几个建议
1. dubbing阶段的时候，合成音频后，将新的音频和原来的音频同事保留，合并到视频，这样方便切换不同的音轨
2. 看到可以使用GPT-SoVITS，是否可以直接调用本机的GPT-SoVITS的服务
3. 生成的字母文件是否可以单独通过ffmpeg embed进去，也可以方便进行切换不同的字母

**Comment by colin4k** [comment]
> 很棒的项目，通过这个项目翻译一些学习视频和动画片给小朋友，很有帮助 有几个建议
> 
> 1. dubbing阶段的时候，合成音频后，将新的音频和原来的音频同事保留，合并到视频，这样方便切换不同的音轨
> 2. 看到可以使用GPT-SoVITS，是否可以直接调用本机的GPT-SoVITS的服务
> 3. 生成的字母文件是否可以单独通过ffmpeg embed进去，也可以方便进行切换不同的字母

目前就是使用本地的 GPT-SoVITS

**Comment by Huanshere** [comment]
感谢认可和反馈！

1. 3. 文件都是有的，但是技术上我还没探索过用ffmpeg如何这样压制成可选的，但我知道不少库能实现！会打算在即将推出的商业版中加入此功能！
2. 这个是本机运行的，可以参考安装指南中的如何使用sovits点开查看配置教程~

**Comment by jenningsloy318** [comment]
@Huanshere  谢谢回复

你好还有个问题，我在使用whisperX的时候，它会下载 使用模型，无论是它自己下载的，还是我自己用huggingface的cli下载的，都要提示shasum256不对，我只有把检查sha256sum的代码删除了才能继续运行，运行也没有问题，我是在debian 12上运行的，使用cuda 11.8.


还有是否可以增加配置，我的显卡比较老，不支持f16，所以我改了代码改成int8，是否可以增加一下配置，设置精度为int8

对于tts，是否可以所有的tts的服务都能配置base_url呢

**Comment by Huanshere** [comment]
1. 这个问题是whisperX项目的问题了，每次调用都会验证哈希值，这是第一次有反馈验证错误，我可能不太会解决。
2. 有报告 1050ti不支持float，在 060428e 中新加了逻辑，如果显存 <=6GB 会自动切换到int8
3. tts服务有什么其他的推荐吗？

**Comment by jenningsloy318** [comment]
TTS, 我也只用过fish 和 GPT-SoVITS

我看到merge还是用ffmpeg，我之前用ffmpeg merge多个音频和字幕用的是下面的参数，希望能对你有帮助
```
ffmpeg -i video.mp4 -i audio.m4a  -i subtitles.srt -c:v:0 copy -c:a:0 copy  -c:s:0 mov_text  output.mp4
```

如果是第二个audio，序号就是`-c:a:1 copy` ,第二个字幕 `-c:s:1 mov_text`

**Comment by Huanshere** [comment]
哈哈哈感谢建议！开源版本的合并可能暂时就这样啦~ 商业版本会采用一些字幕组用的合并字幕的专用的库，样式也能定义得比较好看~

**Comment by jenningsloy318** [comment]
理解，期待正式产品
