### ISSUE TITLE
Add GitHub Issue Template Schema Form

### ISSUE THREAD

**Issue by utsavdotdev** [Huanshere/VideoLingo#137]
**Description:**
To streamline the process of creating issues and ensure consistency, we need to add a GitHub issue template schema form. This will help contributors easily provide all the necessary details when reporting bugs, suggesting features, or requesting documentation.

**Requirements:**
1. Create an issue template that includes fields for:
   - Issue Type (Bug, Feature Request,Documentation)
   - Description
   - Steps to Reproduce (for Bug reports)
   - Expected Outcome
   - Additional Context or Screenshots
2. Ensure the template is easy to navigate and fills out the required fields.

**Proposed Changes:**
1. Implement the issue template in `.github/ISSUE_TEMPLATE` folder.
2. Test the template to verify the form fields populate correctly.

**Before and After:**

*Before:*
<img width="978" alt="Screenshot 2024-10-09 at 7 03 35 PM" src="https://github.com/user-attachments/assets/5cf4abc4-6813-4d6a-befa-490f1485cde3">
  
*After:*
<img width="985" alt="Screenshot 2024-10-09 at 7 02 52 PM" src="https://github.com/user-attachments/assets/f3de05cd-db3e-4266-bb7e-9da98f8e6bfc">

**Additional Information:**
If you have any suggestions for extra fields or modifications, please mention them in the comments.

PS: I am willing to submit the Pull Request

**Comment by Huanshere** [comment]
Thank you for your suggestion. I've added it.
