### ISSUE TITLE
Faithfulness translation of block 1 failed after 3 retries.

### ISSUE THREAD

**Issue by CoffeeGeeker** [Huanshere/VideoLingo#140]
您好，总结和翻译这一步提示

![image](https://github.com/user-attachments/assets/f30c62d1-155c-464e-aeea-d9d2e3bbf718)

ValueError: [red]❌ Faithfulness translation of block 1 failed after 3 retries. Please check your input text.[/red]

请问如何提示！

**Comment by Huanshere** [comment]
大概率是敏感内容AI拒绝翻译，可以检查 `output/gpt_log/error.json` 查看具体response是什么原因失败
