### ISSUE TITLE
uvr5_for_videolingo可以支持 mps，速度可以提升非常大

### ISSUE THREAD

**Issue by vanch007** [Huanshere/VideoLingo#146]
def uvr5_for_videolingo(music_file, save_dir, background_file, original_vocal_file):
    MODEL_DIR = load_key("model_dir")
    if torch.backends.mps.is_available():
        device = torch.device("mps")
    elif torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")

**Comment by Huanshere** [comment]
82a5b5a 感谢建议～ 已经加上了！
