### ISSUE TITLE
能不能增加一个 重新生成（Regenerate） 的方法

### ISSUE THREAD

**Issue by jenningsloy318** [Huanshere/VideoLingo#147]
有时候，运行没有报错，但是我们看视频的时候发现，有些翻译可能不准确或者特定词汇不需要翻译，我们手动调整 
两个问题：
1. 我们是调整 `translation_results_for_subtitles.xlsx` 还是 `translation_results.xlsx`
2. 调整玩如果能够不用执行其他步骤，直接重新生成

**Comment by Huanshere** [comment]
精校的过程建议使用 subtitleedits 这个软件，能够和视频对应上来修改字幕，非常好用~ 字幕的校对过程有在开发~
