### ISSUE TITLE
上传本地mp3音频卡running

### ISSUE THREAD

**Issue by somogd** [Huanshere/VideoLingo#149]
先感谢一下，字幕质量相当高！

我用的windows一键体验包，直接从youtube下载视频和本地mp4都没问题，但是上传本地mp3会卡着。
（为啥我要上传本地MP3呢？因为我只想翻译youtube上某个视频里面的一段，所以就先用其他工具下载了视频，截取完，导出的MP3，再用videolingo，这样api能节省几毛钱……）
<img width="1432" alt="截屏2024-10-12 20 11 49" src="https://github.com/user-attachments/assets/e49e5d9a-2e43-44f7-93fc-f2953cfa2441">

**Comment by Huanshere** [comment]
😯这可能是streamlit框架的问题，有可能是mp3的编码跟它的file_uploader的组件冲突了？试试别的文件或者别的wav之类的有没有问题~

**Comment by somogd** [comment]
音频我有的格式是MP3、wav、flac，都不行，那个视频预览框加载不出来，就卡着一遍遍的自动刷新。
 视频格式都没问题🫰

**Comment by Huanshere** [comment]
是大写后缀的问题，已经修复 864078f ～
