### ISSUE TITLE
本地跑通了，但是需要修改几个地方

### ISSUE THREAD

**Issue by mobilestack** [Huanshere/VideoLingo#15]
1. 视频要短，有行代码限制了音频大小不超过25M，否则会在后面报错
2. 在运行streamlit的terminal要把梯子的代理的代码先贴上去，否则可能会爆socks的错误
3. LLM的base url，可能是没有“v1”的，比如deepseek，需要手动改下代码
4. ffmpeg有时安装的版本不对，需要重新安装

**Comment by mobilestack** [comment]
可惜我这个mac电脑，没GPU，生成的sovits质量太差，全是沙沙的声音

**Comment by Huanshere** [comment]
感谢反馈
1. 25MB 是 whisper 官方建议的，对于音频已经能到 1h 以上了，如果实在有太长的建议手动切开视频处理。
2. 嗯对梯子的支持还有待完善，如果有精力可以提 pr～
3. 嗯不需要带 v1，我可以改改代码增加支持
4. ffmpeg 默认应该是拉官方最新的，这个会有什么版本问题吗？能详细说说吗？

另：sovits 竟然还跟 cpugpu 推理有关吗，要不换个底模试试

**Comment by mobilestack** [comment]
25M那个逻辑，如果做限制的话，可以考虑直接中断继续运行，因为很多人会直接帖一个youtube的长视频，然后后续就可能出错，错误的原因是因为文件超过25M，字幕文件就没有生成，但是后续步骤仍然会去读这个文件，然后就报错了

梯子那个，我觉得问题不大，用terminal的人，总会遇到类似的问题，一般应该可以直接想到是网络环境的事情，也就是自己贴一行代码，让terminal获得代理就好

v1这个是可以考虑加个逻辑，感觉可以在config中配置时就写好，放在后面的代码里面，逻辑就隐藏的有点深了

ffmpeg这里，跟本地运行的环境有关，mac下需要在系统装，python环境里面也要装，但是python环境里面，ffmpeg和ffmpeg-python还不一样，另外，还有其他的ffmpeg包，导致我这里遇到了是一个错误的ffmpeg被代码调用了，各种重新安装就好了

sovits这个，我也拿不准，也还在测试。可能跟模型有关。也可能是某个依赖有些问题，原来的那个sovits库我看是python3.9下面的，加上我这个Mac的M1芯片，也不知道是哪里出了问题

**Comment by Huanshere** [comment]
感谢建议，回去都改改～～

**Comment by mobilestack** [comment]
> 感谢建议，回去都改改～～

好，回头代码稳定一些，我想找个大模型修改下里面的python3.12，变成3.10兼容的，然后放在google colab上跑

**Comment by Huanshere** [comment]
嗯实际上就是两三个地方的 print 的格式的问题，colab 的可以改 all in one.ipynb，前面加上 colab 的挂载以及把当前目录加到环境变量就行～之前有过 colab 版后面删了。。。期待贡献！！

**Comment by mobilestack** [comment]
今天早上又想起了这个项目，感觉应该变成一个可以直接用的服务才好，而且要适配多种语言。现在的情况下，没有中等以上的编程水平，要跑通全部的代码，还是有的难度的。

另外，架构上，为了避免一次生成长一点的视频可能带来的问题，最好是支持先对视频分段，在网页先精确分段，然后对小段内容运行翻译，这样即使出错，也只需要对当前小段重新运行

总体来看，基于网页的、对视频操作的系统，的确还是不多，但是用户其实很需要。切割，翻译，配音，都是其中的一部分。视频中对图像的操作也有很多需求。而且可以调用云端算力，可能比本地编辑都快。

**Comment by Huanshere** [comment]
是的现在还在开源测试阶段，等稳定了会打包成好的产品接上云端算力。

多语言和分段也在计划中，回去就做～

**Comment by Huanshere** [comment]
感谢关注和建议😇

**Comment by Qdoraemon** [comment]
请问 运行 streamlit run st.py的时候 。bash: streamlit: command not found 是什么原因吗

**Comment by Qdoraemon** [comment]
已经解决了 是我忘记安装 streamlit了。 pip install streamlit
