### ISSUE TITLE
希望支持 F5-tts

### ISSUE THREAD

**Issue by vanch007** [Huanshere/VideoLingo#152]
https://github.com/SWivid/F5-TTS?tab=readme-ov-file
<img width="795" alt="image" src="https://github.com/user-attachments/assets/4206bc3d-ff72-4cb0-8c91-c8604a8b0b20">
这个可以设置目标时间让 ai 自动调整语速生成。看 demo 效果不错，比现有的调整音频速度到目标时长要好些

**Comment by Huanshere** [comment]
我觉得本质上和变速没有太大区别，最关键还是如何处理不同语言的文本数量的差异，避免过于明显的变速。

这个项目似乎只支持英文。目前还是考虑使用 Azure 这样比较稳定且适用范围宽泛的，以及在尝试用 GPT-SoVITS 这种可以使用参考音频的。

感谢提议～
