### ISSUE TITLE
如果两句话之间停顿了很久，会导致时间轴错误

### ISSUE THREAD

**Issue by assassinliujie** [Huanshere/VideoLingo#154]
比如1:01说了句话 1:20才说了第二句话，然而轴会变成1:01有一个轴 1:05就有第二个轴了，导致后面这个区块的一大堆轴都整体错位

**Comment by Huanshere** [comment]
对现在偶尔会有这种情况，之后会尝试使用更稳健的转录方法，whisperX的字幕还不算很完美

**Comment by assassinliujie** [comment]
> 对现在偶尔会有这种情况，之后会尝试使用更稳健的转录方法，whisperX的字幕还不算很完美

多尝试识别几次可以勉强解决这个问题，请问能否多加一两个按钮，比如加一个只识别不翻译的功能，可以先让我预览一下识别的轴？然后最好是加一个重试按钮，因为有时候识别完翻译好之后感觉不太合适，用aegisub调又有点麻烦，本身视频也不长的时候，直接重试还是更方便一点

**Comment by Huanshere** [comment]
这个问题，应该是由背景声导致的，请问是否在转录前进行了 UVR 人声分离？

**Comment by Huanshere** [comment]
这个确实是技术上的问题，你能否提供视频和 log，我似乎只遇到过时间轴提前出现的问题，但是没有遇到过会影响后续时间轴的问题

**Comment by assassinliujie** [comment]
> 这个确实是技术上的问题，你能否提供视频和 log，我似乎只遇到过时间轴提前出现的问题，但是没有遇到过会影响后续时间轴的问题

我可能没说清楚？因为这个影响后面的轴实际上我猜测log应该是由同一个chunk或者同一句话拆开得到的，过个几句又会回到正常对齐的状态，所以是的，就是你说的那样只有时间轴提前出现的问题

**Comment by Huanshere** [comment]
嗯是的，估计就是某一句的强制对齐过程出现了问题，这个确实是 whisperX 目前的能力限制了，也试过尝试使用 whisper 原生的 word level，但是小问题更多，包括：1. 幻觉，重复遗漏怪词等等。 2. word level 不带标点 3. word level 合并起来和 sentence level 的句子对不上，会有某些单词遗漏。 所以暂时只能使用 whisperX 啦～

**Comment by sijitang** [comment]
我看到log是分割后uvr，然后会分段处理音频，会把沉默的片段去掉然后在转录？

**Comment by Huanshere** [comment]
不会去掉沉默部分，只是人声分离

**Comment by sijitang** [comment]
请教一下大佬，在您的代码里人声分离和转录都做了分段处理，然后在合并，请问这样做的原因是考虑节省资源还是分段处理转录的效果更好。

**Comment by Huanshere** [comment]
单个文件太大会爆炸
