### ISSUE TITLE
请问这个怎么修复

### ISSUE THREAD

**Issue by tomridder** [Huanshere/VideoLingo#158]
Loading WHISPER model: large-v3 ...
No language specified, language will be first be detected for each audio file (increases inference time).
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.4.1. Bad things might happen unless you revert torch to 1.x.
⠴ Transcribing... 0:02:15

**Comment by Huanshere** [comment]
这个不需要修复，whisperX 是这样的哈哈哈哈，官方项目一堆小问题，不影响运行
