### ISSUE TITLE
在1.6.2新版本源码安装时出现报错

### ISSUE THREAD

**Issue by ReiRzior** [Huanshere/VideoLingo#167]
您好，之前的1.3版本可以正常实现源码安装并运行，1.6.2版本在执行完conda activate videolingo指令后执行python install.py时出现以下报错：
Traceback (most recent call last):
  File "D:\VideoLingo\install.py", line 15, in <module>
    from core.pypi_autochoose.pypi_autochoose import main as choose_mirror
ModuleNotFoundError: No module named 'core.pypi_autochoose.pypi_autochoose'; 'core.pypi_autochoose' is not a package
可能是git clone的源问题吗，之前尝试过下载一键安装包再执行虚拟环境源码安装可以运行

**Comment by Huanshere** [comment]
不好意思，这是版本管理略有混乱，一些冗杂文件重构过程的小毛病～现在用 1.6.4 就没问题了～

**Comment by Huanshere** [comment]
9206696 已修复 这确实是个很难发现的 bug QAQ
