### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by Xiongju** [Huanshere/VideoLingo#168]
Looking in indexes: https://download.pytorch.org/whl/cu118
ERROR: Could not find a version that satisfies the requirement torch==2.0.0 (from versions: 2.2.0+cu118, 2.2.1+cu118, 2.2.2+cu118, 2.3.0+cu118, 2.3.1+cu118, 2.4.0+cu118, 2.4.1+cu118, 2.5.0+cu118)
ERROR: No matching distribution found for torch==2.0.0

**Comment by ApexHigh** [comment]
Same issue
