### ISSUE TITLE
在本地磁盘上找不到指定修订版的相应缓存快照文件夹，并且已禁用传出流量。要启用存储库查找和在线下载，请将 'local_files_only=False' 作为输入传递。

### ISSUE THREAD

**Issue by gaood** [Huanshere/VideoLingo#169]
![微信截图_20241018143822](https://github.com/user-attachments/assets/c5808737-26db-47ce-84c6-ce78cb38399e)

1. 这是啥问题喃？

**Comment by ReiRzior** [comment]
出现了相同问题

**Comment by ReiRzior** [comment]
我猜可能是编码格式的问题，在运行项目的一瞬间好像文字是乱码

**Comment by ReiRzior** [comment]
解决了，源码安装启动启动虚拟环境记得加上videolingo XD
```python
conda activate videolingo
```

**Comment by gaood** [comment]
> 解决了，源码安装启动启动虚拟环境记得加上videolingo XD
> 
> ```python
> conda activate videolingo
> ```
 conda activate videolingo 我是提前启动的，仍然报一样的错
怎么加XD喃？ conda activate videolingo XD吗？
 conda activate videolingo XD 不接受多余参数啊

**Comment by ReiRzior** [comment]
XD是表情表示笑不是参数XD, 关闭规则路由代理的vpn，完全按照readme走应该是正常的，你是不是目录没选对

**Comment by Huanshere** [comment]
SSL 网络问题，请询问 gpt 如何让网络能访问外网

**Comment by gaood** [comment]
> SSL 网络问题，请询问 gpt 如何让命令行能访问外网

完全是按照流程走的，能过访问外网

正在 Ping google.com [142.251.179.101] 具有 32 字节的数据:
来自 142.251.179.101 的回复: 字节=32 时间<1ms TTL=64
来自 142.251.179.101 的回复: 字节=32 时间<1ms TTL=64
来自 142.251.179.101 的回复: 字节=32 时间<1ms TTL=64
来自 142.251.179.101 的回复: 字节=32 时间<1ms TTL=64
