### ISSUE TITLE
请检查 output/audio/sovits_tasks.xlsx 中的对应内容并修改

### ISSUE THREAD

**Issue by xiaoqian2020** [Huanshere/VideoLingo#17]
开始配音处理时，运行了一会报错，提示“请检查 output/audio/sovits_tasks.xlsx 中的对应内容并修改”。
excel文档中没有发现特殊字符，倒是有空格。请问这种是什么问题？另外怎么在cmd中继续执行呢？
附件时excel表格内容
[sovits_tasks.xlsx](https://github.com/user-attachments/files/16746921/sovits_tasks.xlsx)

**Comment by Huanshere** [comment]
配音部分功能还不是特别完善。

这个问题在于 task 里的 duration 太短了，要求 2s 的字幕送去 sovits 很容易超出 2s 。

目前程序的逻辑会尽量合并短的部分，确保没有小于 5s 的一段话（好奇你的这个 tasks 为什么会有这么短的）
