### ISSUE TITLE
gpt-4o-audio-preview能应用到这个项目嘛

### ISSUE THREAD

**Issue by 602387193c** [Huanshere/VideoLingo#171]

**Comment by 602387193c** [comment]
这是我发翻译效果，基本可用，但是感觉还不够自然，不知道gpt-4o-audio-preview能应用到这个项目，改善效果
https://www.bilibili.com/video/BV1mnyuYxExf/?spm_id_from=333.999.0.0&vd_source=7351bb1ce0a307c41b60b64ca036a240

**Comment by Huanshere** [comment]
gpt-4o-audio-preview 收费非常高，单纯作为 tts 确实是有些浪费，可以考虑使用国产的中文 tts 平台。会保持关注～谢谢认可！

**Comment by 602387193c** [comment]
![image](https://github.com/user-attachments/assets/7bd9ecca-a75a-4191-aad8-e3f4762d9512)
![image](https://github.com/user-attachments/assets/25a9721a-f255-45a1-91bb-414cc7deae57)
很贵嘛，我这用的这个平台好像不是很贵，不知道哈，难道计算方法不一样？

**Comment by Huanshere** [comment]
哈哈哈看错了，我以为是 realtime api，这个昨天才出的！期待很久了！我试试

**Comment by SomeoneKong** [comment]
audio token的价格还是很贵的

**Comment by Huanshere** [comment]
我靠 200 刀/M 太抢钱了
