### ISSUE TITLE
windows电脑启动 8501端口成功，但是总是卡在 starting vocal separation 这一步

### ISSUE THREAD

**Issue by tomridder** [Huanshere/VideoLingo#177]
starting vocal separation

**Comment by tomridder** [comment]
(videolingo) D:\code\VideoLingo>streamlit run st.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501/
  Network URL: http://192.168.3.10:8501/

╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Starting UVR5 processing                                                                                             │
│ Device: cuda                                                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Processing segment 0: segment_0_600.wav                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Starting vocal separation...

**Comment by tomridder** [comment]
(videolingo) D:\code\VideoLingo>streamlit run st.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501/
  Network URL: http://192.168.3.10:8501/

╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Starting UVR5 processing                                                                                             │
│ Device: cuda                                                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Processing segment 0: segment_0_600.wav                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Starting vocal separation...

**Comment by Huanshere** [comment]
可以打开任务管理器观察显存情况，看看UVR模型是否有在加载

**Comment by tomridder** [comment]
cuda 环境变量配置成功了 ncvv --version 显示cuda版本
gpu显存 没有启动
cudnn 环境变量也配置到了Path 的  C:\\program files\\Nividia\cudnn 
还是卡在 Starting vocal separation...

**Comment by tomridder** [comment]
重启配置 conda虚拟环境解决了
