### ISSUE TITLE
whisper模型本地使用问题

### ISSUE THREAD

**Issue by baiwei0703** [Huanshere/VideoLingo#182]
我已经从huggingface上下载了 BELLE-2/Belle-whisper-large-v3-zh-punct 和 Systran/faster-whisper-large-v3 两个模型。并按照配置文件的路径，放到了cache目录下。但是项目启动开始执行后，依然会再去下载模型。是放置本地模型的姿势哪里不对吗？路径命名有什么特别注意的吗？希望能得到解答

**Comment by Huanshere** [comment]
是的，需要验证哈希值，这个挺麻烦的，也有直接加载本地模型的方法，但还是自动下载比较方便
