### ISSUE TITLE
出现报错Could not locate cudnn_ops64_9.dll

### ISSUE THREAD

**Issue by Turbo1123** [Huanshere/VideoLingo#183]
Loading WHISPER model: large-v3 ... No language specified, language will be first be detected for each audio file (increases inference time). Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.3.3. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint C:\Users\liyunlong\.cache\torch\whisperx-vad-segmentation.bin` Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x. Model was trained with torch 1.10.0+cu102, yours is 2.0.0+cu118. Bad things might happen unless you revert torch to 1.x. ⠴ Transcribing... 0:00:00Could not locate cudnn_ops64_9.dll. Please make sure it is in your library path! Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor 请按任意键继续. . .

**Comment by Huanshere** [comment]
请确保严格按照安装文档，安装 3.10.0 的环境并且安装好 cuda 和 cudnn 并重启

**Comment by gzfanxin** [comment]
每一步都是按照安装文档操作，还是出现这个报错，不知道如何处理，求助！

**Comment by Huanshere** [comment]
检查环境变量，需要把 cudnn 加入系统 Path

**Comment by Taikou92** [comment]
严格按照安装了，环境变量里也有cuda了，还是抱着个错误哎

**Comment by Huanshere** [comment]
用 everything 搜索 cudnn_ops64_9.dll，然后把这个所在目录加入系统环境变量，然后重启

**Comment by kernelpod** [comment]
python没有默认安装在C盘导致的问题
