### ISSUE TITLE
安装报PIP依赖错误

### ISSUE THREAD

**Issue by soragui** [Huanshere/VideoLingo#187]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 2.2.2 requires scikit-learn, which is not installed.
sentence-transformers 2.2.2 requires scipy, which is not installed.
sentence-transformers 2.2.2 requires torch>=1.6.0, which is not installed.
sentence-transformers 2.2.2 requires transformers<5.0.0,>=4.6.0, which is not installed.
torchvision 0.16.0 requires pillow!=8.3.*,>=5.3.0, which is not installed.
torchvision 0.16.0 requires torch==2.1.0, which is not installed.
nicegui 1.4.22 requires fastapi<0.110.0,>=0.109.1, but you have fastapi 0.99.1 which is incompatible.

**Comment by Huanshere** [comment]
似乎不是这个项目的，nicegui 和 fastapi 。请按照文档新建一个 conda 环境。
