### ISSUE TITLE
No language specified,  Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor

### ISSUE THREAD

**Issue by zjuLiuKaihua** [Huanshere/VideoLingo#188]
第一次运行本地wisper运行有以下报错，请问问题在哪
Loading WHISPER model: large-v3 ...
No language specified, language will be first be detected for each audio file (increases inference time).
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.3.3. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint C:\Users\liukaihua\.cache\torch\whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.0+cu118. Bad things might happen unless you revert torch to 1.x.
⠴ Transcribing... 0:00:00Could not locate cudnn_ops64_9.dll. Please make sure it is in your library path!
Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor

**Comment by Huanshere** [comment]
请按照文档安装 cuda 和 cudnn 后重启。
