### ISSUE TITLE
使用 GPT_SoVITS 配音时出错

### ISSUE THREAD

**Issue by HJhao** [Huanshere/VideoLingo#189]
首先感谢作者的出色工作，非常准确和易用，目前已成功将英文视频转录成文本并翻译成流畅的中文字幕，但在尝试用 GPT_SoVITS 进行再配音时遇到了报错

环境：MAC Apple silicon 本地部署

streamlit run st.py 命令行的报错
```
TTS请求失败，状态码: 404
TTS请求失败，切换回模式2重试
TTS请求失败，状态码: 404
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Error ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Error retrying task 732: Error checking duration: Error opening 'output/audio/tmp/840_temp.wav': System error.
```

GPT_SoVITS go-api.command 命令行的报错
```
INFO:     127.0.0.1:55433 - "POST /tts HTTP/1.1" 404 Not Found
```

看起来预期是要先把原音频分割成若干段，保存在 output/audio/tmp 目录下作为任务输入，但实际上没有生成，所以配音时找不到文件

**Comment by Huanshere** [comment]
感谢认可~检查sovits tasks.xlsx 看看840对应的文本是不是输入gptsovits有问题。

**Comment by HJhao** [comment]
从 1-840 所有的片段输入 gptsovits 都报了上面的 404 错误了，不是只有 840。我打开 output/audio/tmp/ 目录里面是空的

**Comment by Huanshere** [comment]
哦Mac，需要根据VL的提示手动打开gptsovits的api
