### ISSUE TITLE
语音生成失败，控制台提示400的一种问题处理

### ISSUE THREAD

**Issue by lonrencn** [Huanshere/VideoLingo#190]
有可能是ntlk分词词库没装
···python
   import nltk
   nltk.download('averaged_perceptron_tagger_eng')
```
这样安装后，就正常了。

**Comment by Huanshere** [comment]
什么tts方法？

**Comment by lonrencn** [comment]
> 什么tts方法？

GPT-sovite

**Comment by Huanshere** [comment]
这个400错误是出现在vl的命令行中还是弹出的gptsovits的api命令行中？

**Comment by lonrencn** [comment]
出现在vl里，因为400出现就不往下进行了，弄好了以后，我发现生成不出来，再研究的GPT-sovite，最后把API设置好了。
