### ISSUE TITLE
工作流中的提示词设置，用户自定义的配置文件

### ISSUE THREAD

**Issue by lonrencn** [Huanshere/VideoLingo#193]
真针一些翻译需求，最好能灵活处理提示词，把提示词放在config文件里。

**Comment by derlio** [comment]
提示词也是工作流的一部分，完全暴露给用户自定义，可能影响工作流，我只觉得把一些特有名词支持让用户自定义，虽然我看到api请求会自己提取一些关键字指定，但有些名词还是会有变化，最终翻译的前后不一致

**Comment by Huanshere** [comment]
可以修改prompt_storage.py 里面的prompt实现，把提示词放在config中会导致prompt在两个文件中出现，不利于prompt的调整。

**Comment by lonrencn** [comment]
> 可以修改prompt_storage.py 里面的prompt实现，把提示词放在config中会导致prompt在两个文件中出现，不利于prompt的调整。

这一改，项目的工作流不就全改了吗。现在的提示做技术教程翻译非常好，可以当成默认值。

**Comment by Huanshere** [comment]
可以修改一些翻译的语气的指令~
