### ISSUE TITLE
第二次运行爆错

### ISSUE THREAD

**Issue by galaxyrev** [Huanshere/VideoLingo#194]
![image](https://github.com/user-attachments/assets/1c0e99c8-18aa-4085-8a93-9991184612d0)
![1111](https://github.com/user-attachments/assets/e227e741-c090-4027-90d7-84a54a150e6f)
###为什么关闭videoLingo后再次运行就爆错，还得安装一次whisper,执行那个python install.py命令###

**Comment by lonrencn** [comment]
这是youtube下载的库，是不是上次没下全。调用时报错

**Comment by galaxyrev** [comment]
不是，每次都要执行这个命令，不然关闭程序后就一直会报缺少模块，哪怕pip install 这个模块，也会有下个模块缺失
![image](https://github.com/user-attachments/assets/32e375f6-9bf1-471b-bf2a-61a2b399ef49)
dan但执行python install.py安装whisper至少要10分钟，每次这样运行项目就恼火

**Comment by galaxyrev** [comment]
![45352fe39e4c74263a3a6ee365775ab](https://github.com/user-attachments/assets/ecf93dcf-614d-4d90-b50f-757382239e2c)
![45352fe39e4c74263a3a6ee365775ab](https://github.com/user-attachments/assets/e3694322-411a-4ebf-b6cf-a186e5fdc06b)
![10eaa990e56f0cf6685b2e19fd78f97](https://github.com/user-attachments/assets/73dd9633-c640-46f3-a43b-4fed46e6410d)
我想用中文转录成英文，但是也会报错

**Comment by Huanshere** [comment]
这是cuda和cuddn没有下载安装 请参照文档
