### ISSUE TITLE
Empty value for sub-key 'direct' in item 10

### ISSUE THREAD

**Issue by zeekzen** [Huanshere/VideoLingo#196]
转录完成、句子切分完成，使用claude翻译时报错：Empty value for sub-key 'direct' in item 10
查看了gpt_log/error.json，发现报错的句子中没有文字，是
```json
"10": {
                "origin": "... ...",
                "direct": "……"
},
```
所以猜测，如果whisperX转录出来的句子是纯标点符号而没有文字的话，就会报错。
临时解决方法：删掉output/log/cleaned_chunks.xlsx 、sentence_splitbymeaning.txt 、 sentence_splitbynlp.txt里面有问题的那句话，重试即可

**Comment by Huanshere** [comment]
嗯这个项目早期会检查返回结果是否有内容，刚刚在 77cceb2 中去掉了这个检查，感谢反馈！~
