### ISSUE TITLE
能不能在反馈控制台的日志中加入时间位置，这样即能看到进度，也能定位出问题的位置，可以及时核对

### ISSUE THREAD

**Issue by lonrencn** [Huanshere/VideoLingo#197]
能不能在反馈控制台的日志中加入时间位置，这样即能看到进度，也能定位出问题的位置，可以及时核对

**Comment by Huanshere** [comment]
具体是哪个步骤呢？

**Comment by lonrencn** [comment]
就是第一步，翻译，老是报错的那一步，只能看到 原文  翻译  建议 free 那步。我现在把  i 的值打出来了，能看到进度，如果能有i/total，就好了。
因为这个步骤是报错频率最高的，最好能定位出问题的位置，10几分钟的视频，可以重新跑一遍，一小时的，如果不能手动处理，要重新跑太累了，又给那些用收费llm的用户，增加大量成本。

**Comment by Huanshere** [comment]
使用claude3.5对于99%的视频不会报错~

**Comment by lonrencn** [comment]
付费是对白嫖党的侮辱~呵呵

**Comment by lonrencn** [comment]
我用kimi也不报错，现在只要不去和VL争抢GPU调用，就不会报错了。现在试到了这一步
