### ISSUE TITLE
能不能采用逐级调用模型的办法来消除报错

### ISSUE THREAD

**Issue by lonrencn** [Huanshere/VideoLingo#198]
就是如果得不到好的结果，就调用另一个模型，如果还不行，再来个兜底方案，然后把这个位置标记出来，提示用户。
这样就更容易做错误处理，而不是现在就和抽卡一样，不知道哪次能全通过。

**Comment by Huanshere** [comment]
很好的建议！SaaS商业版目前采用了这个思路（月底推出），开源版本为了方便配置和更改进行研究，不会考虑进行复杂的多llm设置

**Comment by lonrencn** [comment]
这个项目的代码工程，逻辑非常清晰，非常适合拿到手二开，代码和说明的版式，是教科书级别的，非常值得学习！
