### ISSUE TITLE
不能识别claude官方api key

### ISSUE THREAD

**Issue by bingood** [Huanshere/VideoLingo#199]
直接调用官方apikey，基础url填https://api.anthropic.com 或 https://api.anthropic.com/v1 都显示密钥无效。

自己修改了下ask_gpt函数，可以调用了，但测试下来，gpt-4o-mini翻译正常，反而调用claude-3-5-sonnet-20241022总是报错，显示Exception: JSON parsing still failed after 3 attempts: ❎ API response error: Missing required sub-key(s) in item 12: free

难道claude-3-5-sonnet-20241022还不如gpt-4o-mini？

**Comment by assassinliujie** [comment]
我建议你可以试试看先用oneapi中转把claude的格式转成GPT的看看

**Comment by Huanshere** [comment]
检查output/gpt_log/error.json 查看响应，claude对于敏感内容容易拒绝

**Comment by assassinliujie** [comment]
> 同样问题，claude-3-5-sonnet-20241022，官方Key, base url https://api.anthropic.com/v1 ,显示 API key is invalid
> 
> 换了几次key，重装几次依然如此
> 
> Unexpected error occurred: Error code: 404 - {'type': 'error', 'error': {'type': 'not_found_error', 'message': 'Not Found'}}
> 
> API key is invalid

作者开发时使用的api提供商采用的是oneapi这个项目，该项目应该把Claude api返回的格式整合成了gpt的格式。建议你也采用oneapi进行转换
