### ISSUE TITLE
一键启动.bat配置错误.....

### ISSUE THREAD

**Issue by yxc0915** [Huanshere/VideoLingo#2]
一键启动.bat配置错误

**Comment by yxc0915** [comment]
`Fatal error in launcher: Unable to create process using '"f:\VideoLingo\.venv\Scripts\python.exe"  "D:\BaiduNetdiskDownload\VideoLingo\VideoLingo\.venv\Scripts\streamlit.exe" run st.py': ???????????

请按任意键继续. . .`

**Comment by Huanshere** [comment]
百度网盘里新的包修复了问题，发现是streamlit的锅，需要重新下载⏬ 谢谢反馈🙏
