### ISSUE TITLE
运行whisperX的时候，模型报错，如何绕过？

### ISSUE THREAD

**Issue by zwyzjj** [Huanshere/VideoLingo#200]
我打开梯子，就会报SSL错误，关闭梯子会提示连接超时，我把huggingface的faster-whisper-large-v3模型下载到_model_cache文件夹中，运行程序还是回去huggingface下载模型，有什么办法可以直接本地运行，不要去huggingface下载模型嘛？
![image](https://github.com/user-attachments/assets/7ca7b447-2634-4285-9dd9-90249c88191a)

**Comment by Huanshere** [comment]
网络问题暂时没有好的办法，有可以纯本地load的方法，请自行探索~
