### ISSUE TITLE
youtube最新的视频文件格式不支持

### ISSUE THREAD

**Issue by lonrencn** [Huanshere/VideoLingo#201]
youtub新上传的视频，下载下来是.mkv的，平台不支持这种格式
https://www.youtube.com/watch?v=MCVcAAoDJS8&list=PLK8U0kF0E
文件下载了，但是提示格式不支持

**Comment by lonrencn** [comment]
就是提示格式不支持

**Comment by Huanshere** [comment]
<img width="761" alt="image" src="https://github.com/user-attachments/assets/826e27ad-33d4-4f95-b062-3c2f5ed04775">
我这儿可以正常下载，具体是什么地方的报错呢？

**Comment by lonrencn** [comment]
我这这两天也没出过问题。

**Comment by Huanshere** [comment]
感谢反馈~

**Comment by lonrencn** [comment]
> 感谢反馈~

请问一下大佬，为什么这里的cuda非要用11.8，现在大多不是都12了吗？

**Comment by Huanshere** [comment]
whisperX 对环境要求非常严格。

**Comment by lonrencn** [comment]
谢谢解惑

**Comment by lonrencn** [comment]
whiperX本地没有其它语言的翻译模型吗

**Comment by Huanshere** [comment]
whisperX 不是翻译模型 你指的是什么？

**Comment by Huanshere** [comment]
支持，但是本项目依赖于标点进行断句，不建议使用于其他语言
