### ISSUE TITLE
进程bug 本地大模型 报错

### ISSUE THREAD

**Issue by lonrencn** [Huanshere/VideoLingo#204]
File "/home/*/miniconda3/envs/videolingo/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/*/videolingo-project/VideoLingo/core/step4_2_translate_all.py", line 49, in translate_chunk
    translation, english_result = translate_lines(chunk, previous_content_prompt, after_content_prompt, things_to_note_prompt, theme_prompt, i)
  File "/mnt/*/videolingo-project/VideoLingo/core/translate_once.py", line 69, in translate_lines
    prompt2 = get_prompt_expressiveness(faith_result, lines, shared_prompt)
  File "/mnt/*/videolingo-project/VideoLingo/core/prompts_storage.py", line 193, in get_prompt_expressiveness
    "origin": value['origin'],
KeyError: 'origin'

```以下代码测试两个文件
import json
import os

def load_json(file_path):
    """从文件中加载 JSON 数据"""
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"File not found: {file_path}")
    
    with open(file_path, 'r', encoding='utf-8') as file:
        data = json.load(file)
    return data

def display_json_structure(data, indent=0):
    """递归显示 JSON 数据的键值结构"""
    if isinstance(data, dict):
        for key, value in data.items():
            print(' ' * indent + f"{key}:")
            display_json_structure(value, indent + 2)
    elif isinstance(data, list):
        for index, item in enumerate(data):
            print(' ' * indent + f"[{index}]:")
            display_json_structure(item, indent + 2)
    else:
        print(' ' * indent + f"{data}")

def main():
    # 指定 JSON 文件路径
    file1_path = '/home/*/videolingo-project/VideoLingo/output/gpt_log/translate_expressiveness.json'
    file2_path = '/home/*/videolingo-project/VideoLingo/output/gpt_log/translate_faithfulness.json'

    # 读取 JSON 文件
    try:
        json_len1 = len(load_json(file1_path))
        json_len2 = len(load_json(file2_path))
        print(json_len1,json_len2)
        for i in range(44):
            chunk1_len = len(load_json(file1_path)[i]["response"])
            chunk2_len = len(load_json(file2_path)[i]["response"])
            print(f'{chunk1_len} :: {chunk2_len}')
        # data2 = len(load_json(file2_path)[0]["response"])
    except FileNotFoundError as e:
        print(e)
        return

    # 显示 JSON 文件的键值结构
    # print(f"Structure of {file1_path}:")
    # display_json_structure(data1)
    # print("\n" + "=" * 50 + "\n")
    print(f"*******************************************************")
    # print(f"Structure of {file2_path}:")
    # display_json_structure(data2)

if __name__ == "__main__":
    main()
```
结果是
43 44   #整体长度比较

6 :: 6
10 :: 10
10 :: 10
10 :: 10
9 :: 10
10 :: 9
8 :: 8
8 :: 8
10 :: 10
10 :: 10
10 :: 10
9 :: 9
7 :: 7
10 :: 10
10 :: 10
10 :: 10
10 :: 10
10 :: 10
9 :: 10
7 :: 9
10 :: 7
9 :: 9
10 :: 10
10 :: 10
10 :: 10
9 :: 9
10 :: 10
9 :: 9
8 :: 10
10 :: 8
9 :: 9
10 :: 10
10 :: 10
10 :: 10
10 :: 10
9 :: 10
10 :: 9
10 :: 10
9 :: 10
3 :: 9
10 :: 9
9 :: 10
8 :: 3

本地大模型ollama 开4路并发，4个worker

**Comment by lonrencn** [comment]
又跑了一遍，这次通过了，两个.json结果如下
44 44
6 :: 6
10 :: 10
10 :: 10
10 :: 10
10 :: 10
9 :: 9
8 :: 8
9 :: 9
10 :: 10
10 :: 10
10 :: 10
9 :: 9
7 :: 7
10 :: 10
10 :: 10
10 :: 10
10 :: 10
10 :: 10
10 :: 10
9 :: 9
7 :: 7
9 :: 9
10 :: 10
10 :: 10
10 :: 10
9 :: 9
9 :: 9
9 :: 9
10 :: 10
8 :: 8
9 :: 9
10 :: 10
10 :: 10
10 :: 10
10 :: 10
9 :: 10
10 :: 9
10 :: 10
10 :: 10
9 :: 9
9 :: 9
3 :: 8
8 :: 10
10 :: 3
这次整个过程，GPU全程只给lingo用，结果就通过了。但是最后三行还是顺序错了。
看来是因为其它服务与workers抢gpu导致的并发错误
这个视频完全没有手动干预，完全是平台跑出来的。没有出现格式不支持的提示。
https://www.bilibili.com/video/BV1yf1uYWEmY/?vd_source=5b3650b0f6fab221aa0e101efbf77ad0

**Comment by Huanshere** [comment]
检查output/gptlog/error.json 查看错误原因，估计是小模型没有正确遵循json格式，不建议使用小模型的原因在文档中也说明了

**Comment by lonrencn** [comment]
> 检查output/gptlog/error.json 查看错误原因，估计是小模型没有正确遵循json格式，不建议使用小模型的原因在文档中也说明了

这个问题error.json里没有记录
之前用小模型，和非官方训练的模型试了，qwen2:7b也试了，一大片错误，没法用。
只有qwen2.5b:32b可以，70b没装，不知道效果。

**Comment by Huanshere** [comment]
我试过 qwen2.5 70B 偶尔报错 以后会尝试用数据集来训练私有模型

**Comment by lonrencn** [comment]
真有心白嫖的，就自己弄了，把错误定位出来，手动处理一下就行了。
