### ISSUE TITLE
支持自定义最后的视频和字幕合并FFmpeg命令或参数

### ISSUE THREAD

**Issue by qixing-jk** [Huanshere/VideoLingo#205]
最后合并的时候性能压力最大，但默认运行时，不会调用GPU加速，CPU处理速度和压力过大

**Comment by Huanshere** [comment]
在core目录的step7，可以修改了提交pr~ gpu加速的ffmpeg效果确实很好

**Comment by hanco1** [comment]
> 在core目录的step7，可以修改了提交pr~ gpu加速的ffmpeg效果确实很好

preset调多少好啊
