### ISSUE TITLE
Have you considered adding the functionality to run VideoLingo on the CPU instead of the GPU?

### ISSUE THREAD

**Issue by brownplayer** [Huanshere/VideoLingo#207]

**Comment by brownplayer** [comment]
OK，l know ,thank you for you reply 😄

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/28/2024 20:10 |
| To | Huanshere/VideoLingo ***@***.***> |
| Cc | Liu ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Huanshere/VideoLingo] Have you considered adding the functionality to run VideoLingo on the CPU instead of the GPU? (Issue #207) |

Tested, extremely slow. Recommend to use colab if you don't have a gpu~

**Comment by lonrencn** [comment]
(use CPU)  will very very slow!
