### ISSUE TITLE
建议修改文件命名方式

### ISSUE THREAD

**Issue by colin4k** [Huanshere/VideoLingo#209]
以字幕为例，假如原始文件名为 a.mkv，原始语言为 en，目标语言为 zh，则生成的字幕文件分别为
a.en.srt
a.zh.srt
a.enzh.srt
a.zhen.srt
视频文件类似，这样后续使用省事很多。

**Comment by lonrencn** [comment]
饭都喂到嘴边了，就不能自己动动手。

**Comment by Huanshere** [comment]
暂不考虑重命名，因为现在的命名是为了确保程序间沟通用，烦请手动重命名
