### ISSUE TITLE
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by temmmos** [Huanshere/VideoLingo#210]
用源码安装启动后提示
![QQ20241028-231413](https://github.com/user-attachments/assets/0b5e0682-a5ad-4aee-9371-100d996f5a96)
根据相同问题已更改numpy==1.26.4未能解决

**Comment by Huanshere** [comment]
是否是源码安装 python=3.10.0 numpy==1.26.4 在哪一步产生的问题？

**Comment by temmmos** [comment]
> 是否是源码安装 python=3.10.0 numpy==1.26.4 在哪一步产生的问题？

是源码安装的python=3.10.0 
在最后一步输入命令streamlit run st.py启动的时候出现的问题，并且如果改用 一键启动.bat 来启动会出现错误

**Comment by Huanshere** [comment]
暂时没有见到有人复现，之前 2.0.0 版本会出现，更换到 1.26.4 就好了，能否重新安装再看看？

**Comment by hanco1** [comment]
> 暂时没有见到有人复现，之前 2.0.0 版本会出现，更换到 1.26.4 就好了，能否重新安装再看看？

安装1.26.4np会报blis 1.0.1 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
thinc 8.3.2 requires numpy<2.1.0,>=2.0.0; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.

**Comment by Huanshere** [comment]
请检查 python 版本是否 3.10.0，以及是什么系统呢？似乎是 nlp 会用到这个，请检查是否为spacy==3.7.6

**Comment by Huanshere** [comment]
是否按照的 requirements 安装的？里面写了spacy==3.7.6，是不是安装过程报错了没管呀
