### ISSUE TITLE
请问报错这个什么情况LocalEntryNotFoundError: Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass 'local_files_only=False' as input.

### ISSUE THREAD

**Issue by lmzg** [Huanshere/VideoLingo#216]
<img width="366" alt="Snipaste_2024-10-30_16-34-18" src="https://github.com/user-attachments/assets/72107959-d397-4894-8826-b4468ec832f7">

**Comment by Huanshere** [comment]
v1.7 已解决，这是因为你的命令行无法连接 hf

**Comment by ThieFL** [comment]
你好，我用的1.7爲什麽仍然會有這個報錯
![Uploading QQ20241031-172930.png…]()

**Comment by ThieFL** [comment]
你好，我用的1.7爲什麽仍然會有這個報錯
![Uploading QQ20241031-172930.png…]()

**Comment by Huanshere** [comment]
安装步骤说明已写，如果你无法连接到 hf ，可以手动下载模型

**Comment by ReiRzior** [comment]
哈哈哈这是一个Huan复现不了解决不了的问题，因为他在海外。
使用conda创建虚拟环境后，请执行以下语句使虚拟环境正常使用代理
`conda install certifi`
