### ISSUE TITLE
关于长音频文件中 split_audio 方法查找分割点的问题请教

### ISSUE THREAD

**Issue by beyondkevin** [Huanshere/VideoLingo#222]
### 问题描述

在 `split_audio` 方法中，我注意到存在一个逻辑问题（也可能是我理解错误，希望能得到解答），可能会影响音频分割的准确性。

### 具体位置

- **文件**: `core/all_whisper_methods/whisperXapi.py`
- **方法**: `split_audio`

### 问题细节

在 `split_audio` 方法中，`target_duration` 被设定为一个固定值（例如20分钟）。随着循环的进行，`start` 的值会不断增加。当 `start` 的值超过 `target_duration` 时，后续的静音结束时间很可能会始终大于 `target_duration`。这使得在查找静音结束时间时，程序可能无法找到合适的分割点。

具体来说，以下代码段中的逻辑可能会导致问题：

```python
split_point = next((t for t in silence_end_times if t > target_duration), None)
```

在处理长音频时，`silence_end_times` 中的值可能会始终大于 `target_duration`，从而导致程序无法找到合适的分割点。

### 提问

我想请教一下，您是否考虑过这种情况？在处理长音频时，如何确保能够找到合适的分割点？期待您的解答，谢谢！

**Comment by Huanshere** [comment]
368b28e 感谢建议，是个小错误，已经修复～ 之前的代码再找不到会直接在 20 处切割，没有正确找到长视频的静音切割点
