### ISSUE TITLE
建议增加自定义专业词汇表和hooks功能

### ISSUE THREAD

**Issue by zeekzen** [Huanshere/VideoLingo#226]
# 提供专业词汇表和特定翻译表达
用户可以为翻译大模型提供一个专业词汇表，让大模型作为翻译参考，提高正确性，例如可以用一个json描述词汇表
```json
[
    {
        "en": "AAA",
        "zh": "专业领域特殊表达" 
    },
    ... ...
]
```
# 为任务提供hooks
有时候任务执行时间比较长，想实现当任务报错、完成等状态时，可以执行用户提供的python/sh/bat脚本，用户可以在脚本里执行任意自己的代码，如关机、发消息通知、重试任务、归档、上传等。

**Comment by Huanshere** [comment]
专业词汇表和翻译风格会考虑加入~ hooks功能暂不考虑，可以自行添加

**Comment by zeekzen** [comment]
> 专业词汇表和翻译风格会考虑加入~ hooks功能暂不考虑，可以自行添加

好的，感谢回复，看了下代码，各个step很清晰👍🏻，自己加起来应该不麻烦。
