### ISSUE TITLE
更新最新代码后 分离音频好慢

### ISSUE THREAD

**Issue by tomridder** [Huanshere/VideoLingo#227]
Mac os   M2
10月28号之前代码很快
只会很慢

**Comment by Huanshere** [comment]
因为之前的版本不强制做人声分离，容易产生对齐的错误。

**Comment by tomridder** [comment]
soga 所以现在 弱模型也不容易报错了 是吧

**Comment by Huanshere** [comment]
这俩是分开的~ 之前如果BGM过大不做背景声分离，whisperX在强制对齐的步骤，会在一小块地方积累一大堆单词，导致后续llm切割开以后就找不到时间轴了。

弱模型的问题还是依然存在，不建议使用~

**Comment by tomridder** [comment]
Soga 那我只翻译 不做中声 应该可以回退代码了 😂
