### ISSUE TITLE
开源版建议url不自动补全，兼容国产大模型

### ISSUE THREAD

**Issue by dabao005** [Huanshere/VideoLingo#229]
发现很多国产大模型不是 v1/xxxx的形式。

**Comment by Huanshere** [comment]
使用claude外的模型容易报错，对模型智力要求较高，而且对每一家模型做兼容难度较大，暂不考虑，仅考虑接入openai格式

**Comment by lonrencn** [comment]
> 发现很多国产大模型不是 v1/xxxx的形式。

推荐你把所有的大模型都放到one-api上统一管理，这样就会兼顾openai的地址格式了

**Comment by dabao005** [comment]
> > 发现很多国产大模型不是 v1/xxxx的形式。
> 
> 
> 
> 推荐你把所有的大模型都放到one-api上统一管理，这样就会兼顾openai的地址格式了

感谢，完美解决我问题了
