### ISSUE TITLE
demucs_vl 可以使用 mps 加速

### ISSUE THREAD

**Issue by vanch007** [Huanshere/VideoLingo#231]
self.update_parameter(
            device="cuda" if is_cuda_available() else "mps" if torch.backends.mps.is_available() else "cpu",
            shifts=shifts,
            overlap=overlap,
            split=split,
            segment=segment,
            jobs=jobs,
            progress=True,
            callback=None,
            callback_arg=None,
        )
        苹果的 mps 支持大部分 torch 推理，whisperX 还不支持

**Comment by Huanshere** [comment]
4e6e552 感谢建议，已经加入～
