### ISSUE TITLE
502 

### ISSUE THREAD

**Issue by soragui** [Huanshere/VideoLingo#235]
https://yunwu.zeabur.app/  这个报 502 咋办

**Comment by ktmswzw** [comment]
不稳定，用本地模型或者换其他的，我目前测试了通过的是LM studio，加载本地 Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf 模型，token随便 api写好 http://localhost:1234 就可以跑了

**Comment by zeekzen** [comment]
> 不稳定，用本地模型或者换其他的，我目前测试了通过的是LM studio，加载本地 Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf 模型，token随便 api写好 http://localhost:1234 就可以跑了

请问本地模型的效果怎么样，和推荐的在线模型（claude）相比呢

**Comment by Huanshere** [comment]
云雾的服务之前掉线了 现在好了

**Comment by Huanshere** [comment]
强烈不建议使用本地的。

**Comment by zeekzen** [comment]
> 不稳定，用本地模型或者换其他的，我目前测试了通过的是LM studio，加载本地 Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf 模型，token随便 api写好 http://localhost:1234 就可以跑了



> 强烈不建议使用本地的。

我也尝试了使用本地模型，Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf，跑是能跑通，但是效果确实比在线模型差很多。
