### ISSUE TITLE
whisper model和torch版本不匹配

### ISSUE THREAD

**Issue by BlackChoco** [Huanshere/VideoLingo#237]
📥 Loading local WHISPER model: ./_model_cache/large-v3 ...
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.3.3. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../.cache/torch/whisperx-vad-segmentation.bin`
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpf3vi2e9m
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpf3vi2e9m/_remote_module_non_scriptable.py
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.0+cu118. Bad things might happen unless you revert torch to 1.x.
⠦ Transcribing... 0:00:06Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}
Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor
Aborted (core dumped)

我按照步骤进行安装了，但是会出现model和torch版本不匹配的问题

**Comment by BlackChoco** [comment]
我需要降级安装model对应的版本吗？

**Comment by BlackChoco** [comment]
尝试降级安装model需要库的版本后，又会报其他的错

**Comment by zeekzen** [comment]
看上去不是torch版本问题
```sh
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.0+cu118. Bad things might happen unless you revert torch to 1.x.
```

有这两行也没关系，不影响。
我感觉主要是因为下面的报错
```sh
⠦ Transcribing... 0:00:06Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}
Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor
```
是不是没有安装cudnn，或者没有把cudnn路径加到环境变量

**Comment by colin4k** [comment]
cudnn 安装的版本不对，要 8.x

**Comment by cgl13207205048** [comment]
我也是这个报错，cudnn按照版本也装的

**Comment by Huanshere** [comment]
版本不匹配那个错误可以忽略，Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}这个是因为 cuda 和 cudnn 安装的问题，如果按照说明安装了，那就是因为没有放在系统路径中

**Comment by Brzjomo** [comment]
你需要修改CUDNN的环境变量，默认的是不正确的。
默认：
C:\Program Files\NVIDIA\CUDNN\v9.3\bin
要改为：
C:\Program Files\NVIDIA\CUDNN\v9.3\bin\12.6
