### ISSUE TITLE
config 是否可以有更多说明和设置

### ISSUE THREAD

**Issue by neohob** [Huanshere/VideoLingo#24]
1. 视频分辨率是否可以在 config 里面设置，或者在UI 界面上选择？
2. config 里面是否可以有更多说明，比如我如何使用 deepseek 或者直接用 openai，claude，groq等AI 接口？
3. 是否有可能可以更多的手动分步，比如有的视频到翻译就可以停止，后面步骤暂时不执行了，我只需要翻译字幕
4. 是否可以支持多人说话区分？

谢谢

**Comment by neohob** [comment]
谢谢作者回复

3. 里面有好几个步骤，比如 1. 下载  2. 人声分离 3. 语音识别 4. 翻译成srt .... ，每个步骤都可以有成果文件，各取所需，因为每个步骤都有很大的调整空间，整合一起从头到尾并不是每个人想要的效果。

**Comment by Huanshere** [comment]
那对于现在的流程 你觉得在哪几个地方拆开比较合适呢 可以看看all in one.ipynb的分步骤

**Comment by neohob** [comment]
有 pynb 就都可以了，可以自己控制，谢谢作者
