### ISSUE TITLE
POST /tts HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by ryonWang** [Huanshere/VideoLingo#252]
<img width="1146" alt="截屏2024-11-11 14 39 49" src="https://github.com/user-attachments/assets/65ad11ea-c62d-47c2-ae63-0091c53cc00e">
<img width="482" alt="截屏2024-11-11 14 39 36" src="https://github.com/user-attachments/assets/f03f8164-4856-489c-a4fd-b5c1acd10908">
集成soVITS的时候，本地vits已经联调并启动成功，并可以独立执行。但是lingo再启动调用的时候，报/tts这个请求400，我看了请求json的申明，是 json=payload，不知道是不是这里问题，谁遇到了，怎么改的，请赐教

**Comment by mthezi** [comment]
选的是不是模式3

**Comment by ryonWang** [comment]
> 选的是不是模式3

选的模式1

**Comment by mthezi** [comment]
检查一下，提供的查看音频存不存在，是否遵循对应格式  xxx_参考文本

**Comment by ryonWang** [comment]
> 检查一下，提供的查看音频存不存在，是否遵循对应格式 xxx_参考文本

是的，我是按照参考来设置的，并且放置到了相应的文件夹内。截图里，我这个名称是否标准
<img width="253" alt="截屏2024-11-11 15 30 00" src="https://github.com/user-attachments/assets/a00c8c03-85d9-458c-a347-c1ade4596cd6">

**Comment by mthezi** [comment]
![image](https://github.com/user-attachments/assets/6753f2cc-c7c0-40bf-aa1d-4819feb64211)

在这里打印payload，看传过去给gpt-sovits的数据

**Comment by ryonWang** [comment]
> ![image](https://private-user-images.githubusercontent.com/151412975/384830508-6753f2cc-c7c0-40bf-aa1d-4819feb64211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTEwNjYsIm5iZiI6MTczMTMxMDc2NiwicGF0aCI6Ii8xNTE0MTI5NzUvMzg0ODMwNTA4LTY3NTNmMmNjLWM3YzAtNDBiZi1hYTFkLTQ4MTlmZWI2NDIxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwNzM5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjRlZTJhNTkwZGZjMDBlMzQ5ZTVjZGUzN2ZjODQwMDAzZDE3ZjE1OThmMzlhZTUwYWNjYmYyOTI2ODFiOTA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jqg3SsPvTo83lv5KuMXwNoy1iUtmFQRyn1bjGQDfozo)
> 
> 在这里打印payload，看传过去给gpt-sovits的数据
print了，我没看出有啥问题，我发截图帮忙看下是否有问题
<img width="1127" alt="截屏2024-11-11 15 50 12" src="https://github.com/user-attachments/assets/97d6f757-e8d3-4fd3-be25-1b5f9d072e79">

**Comment by mthezi** [comment]
那就检查一下这个文件存不存在，有没有读取权限。
如果还是无法解决，那么就打开gpt-sovits去debug，看它具体报什么错

**Comment by Huanshere** [comment]
鉴于此 bug 无法复现，我先关闭了
