### ISSUE TITLE
关于在云端使用GPT-SoVITS

### ISSUE THREAD

**Issue by huang5656151** [Huanshere/VideoLingo#257]
我将代码部署在云端，希望在配音部分使用GPT-SoVITS-v2，直接运行报系统不支持，只支撑Mac和Windows，我云端是Autodl的Linux，有没有大佬帮支支招，非常感谢！

**Comment by Huanshere** [comment]
本地跑的 Sovits 是下载了整合包的，云端的 sovits 还没有研究过如何部署，可以看看有没有社区贡献的版本

**Comment by ysxk** [comment]
换星海智算呗，有winserver2022，实测可以用gpt-sovitsv2
只要不是对外开放使用那很舒服的，价格也不贵，4090好像比autodl还便宜
https://gpu.spacehpc.com/user/register?inviteCode=31762701
