### ISSUE TITLE
FFMPEG报错

### ISSUE THREAD

**Issue by assassinliujie** [Huanshere/VideoLingo#259]
NVIDIA GPU encoder detected, will use GPU acceleration.
🎬 Start merging subtitles to video...

[Error occurred during FFmpeg execution.]
自从上个版本开始就会这样，今天更新了之后看描述是修复了，但是还是会报错，没有更多的输出不好定位问题

**Comment by Huanshere** [comment]
请尝试 v2.0 版本，应该修复了大部分 ffmpeg 问题～

**Comment by Huanshere** [comment]
现在还会出现 ffmpeg 报错吗？似乎对于某些视频会出错，暂时未知原因

**Comment by assassinliujie** [comment]
> 现在还会出现 ffmpeg 报错吗？似乎对于某些视频会出错，暂时未知原因

暂时不会了
