### ISSUE TITLE
No AMD GPU Support ?

### ISSUE THREAD

**Issue by Greatz08** [Huanshere/VideoLingo#261]
```
System Requirements:
 CUDA version > 12.4
 NVIDIA Driver version > 550
```
Since these are system requirements so it means it doesnt support AMD GPU's ? if yes then are there any plans to support it in future ?
(Btw i do have NVIDIA GPU still was curious to know because i have amd igpu 780M in my system with which i thought to try this project out too later as it is number 1 igpu so was interested to see its performance hehe so was asking here :-))

**Comment by aklws** [comment]
Can't run it on amd's gpu right now I guess, because whisperx and faster-whisper require cudnn9, which rocm can't do yet.

**Comment by Huanshere** [comment]
Yes whisperX requires cudnn9, which is soooo troublesome...
