### ISSUE TITLE
cudnn_ops64_9.dll识别不到

### ISSUE THREAD

**Issue by ROClucky** [Huanshere/VideoLingo#265]
系统环境有添加，但是cudnn_ops64_9.dll文件一直识别不到
![1](https://github.com/user-attachments/assets/8cc2c481-a3ec-4c08-9faa-d825eb6dcb1b)

![2](https://github.com/user-attachments/assets/4f3a367b-8b61-4002-88f1-d12c981bf696)
![3](https://github.com/user-attachments/assets/6d625050-8573-4038-930b-6d957e527b65)

**Comment by Huanshere** [comment]
v2.0中已经添加说明~需要添加的是12.6的cuda
