### ISSUE TITLE
Why use a third-party ffmpeg?

### ISSUE THREAD

**Issue by jyC23333** [Huanshere/VideoLingo#268]
Hello, an awsome project!!

I'm working on a Linux server. So why use a ffmpeg from an un-official website like this:
```
        elif system == "Linux":
            ffmpeg_exe = "ffmpeg"
            url = "https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz"
```
rather than `apt install`?

Sadly my A100 GPU seems can't accelerate the ffmpeg process, is there some other ways to accelerate?

**Comment by Huanshere** [comment]
This project is developed on Windows. For some unknown reasons, using ffmpeg from conda on Windows causes errors, and installing ffmpeg via Chocolatey is too troublesome for users, so I chose to download it locally. This method was also applied to Linux. However, theoretically, both Linux and Mac have good version management, and ffmpeg installed via apt on Linux should work better. If you try it and find no issues, please feel free to submit a PR. Thank you for your feedback!

**Comment by jyC23333** [comment]
Get it. Thanks!
