### ISSUE TITLE
电脑需要啥配置才能启动呢？？

### ISSUE THREAD

**Issue by GiantLzg** [Huanshere/VideoLingo#27]
我在最后一步启动的时候报错
![1](https://github.com/user-attachments/assets/fc266f46-7ed5-4b8c-990f-61e7df61b0e4)
电脑配置：
![2](https://github.com/user-attachments/assets/ef9a1a22-3da6-47c8-822d-c5ffa9c624d5)

这个segmentation fault的报错是因为我电脑带不动引起的吗？？？

**Comment by Huanshere** [comment]
请问 python 版本是？v0.1 版本最好是 3.12 以上版本，v0.2 现在 3.10 以上就行

**Comment by Huanshere** [comment]
现在版本稳定了应该能支持了～
