### ISSUE TITLE
pandas.arrays_to_mgr报错数组长度必须一致

### ISSUE THREAD

**Issue by Brzjomo** [Huanshere/VideoLingo#270]
部分视频翻译执行到step5的pd.DataFrame({'Source': src, 'Translation': remerged}).to_excel(OUTPUT_REMERGED_FILE, index=False)时，报错arrays_to_mgr数组长度必须一致。
看了下"output/log/translation_results_remerged.xlsx"这个文件只跟翻译纯音频相关，所以目前注释step5和step6相关代码之后，就能正确结束视频翻译的任务。

**Comment by Huanshere** [comment]
请问使用的什么 llm 呢？我在使用推荐的几家模型基本都不会出现翻译行数变少的情况，这个检查是为了最终字幕的稳定

**Comment by asu-gkg** [comment]
Qwen2-72B-Instruct就会出现这个问题

**Comment by Huanshere** [comment]
😂现在默认还是推荐 claude 了，Qwen 还需要很长时间的追赶

**Comment by lanxichan** [comment]
openai 也会报这个错，奇怪的是同一个yt视频，360p的没问题，720（自己加的）和1080都会报错。

**Comment by Huanshere** [comment]
哈哈哈这个和分辨率无关，可能是概率上会出错，gpt4o 可能没有返回完整响应或者漏了句子。

**Comment by lanxichan** [comment]
> 哈哈哈这个和分辨率无关，可能是概率上会出错，gpt4o 可能没有返回完整响应或者漏了句子。

我也是这样想的，只是当时测试过程中**连续稳定重现**所以我才奇怪。 😂

**Comment by Huanshere** [comment]
gpt_log 会记录所有响应并且重复运行的时候会从中读取历史，所以如果没有删除 log 就重新运行其实还是会报同样错误～
