### ISSUE TITLE
prompt允许语序调换

### ISSUE THREAD

**Issue by assassinliujie** [Huanshere/VideoLingo#271]
今天在用qwen尝试直接翻译字幕时，发现在prompt里允许AI调换中文语序能够使得翻译结果更加符合中文习惯，是否可以作为可选功能，比如添加一个步骤，发送多行字幕，检查顺序是否符合习惯，如果不符合就调整顺序这样

**Comment by Huanshere** [comment]
这个问题在原代码中其实是实现了的，只是 Qwen 太保守没有打乱语序，所以建议尝试 claude
