### ISSUE TITLE
step7 gpu_available判断异常

### ISSUE THREAD

**Issue by borzj** [Huanshere/VideoLingo#275]
我的电脑是amd核显, 为什么这里会判断我有NVIDIA GPU.
![image](https://github.com/user-attachments/assets/6b853235-8395-431d-8eca-1882d4bfca05)
而我自己运行check_gpu_available函数的时候却是False
![image](https://github.com/user-attachments/assets/fc3baca6-a2e7-4994-9b34-8abbe9a36512)

**Comment by Huanshere** [comment]
这个 h264_nvenc 应该是仅限于 N 卡的（AMD 显卡应该是使用 h264_amf），对于你的情况，正确显示应该是没有检测到 N 卡。请问具体两个情况是什么呢？听起来像是一键运行显示有 N 卡，单步运行显示没 N 卡？

**Comment by Huanshere** [comment]
确实很奇怪，不是很清楚是什么导致的 QAQ

**Comment by Michael8021** [comment]
同样有这个问题，只有独立A卡

![image](https://github.com/user-attachments/assets/ad328409-4b80-4be2-bbcc-61b43747c4fa)

**Comment by Huanshere** [comment]
是的 之前A卡确实判断有问题，现在修复了~ 感谢反馈！  034bebd
