### ISSUE TITLE
关于huggingface连接不上的问题

### ISSUE THREAD

**Issue by infiniteYuanyl** [Huanshere/VideoLingo#277]
![image](https://github.com/user-attachments/assets/e9851311-acc2-4e01-9fa9-f3aac4cb484a)
看了下好像是whisper的alignmodel导致的，看看有没有大佬知道怎么解决，改成本地加载

**Comment by Huanshere** [comment]
诶难道是 whisperX 指向的日语模型不存在？但我觉得大概率是网络问题？

**Comment by infiniteYuanyl** [comment]
> 诶难道是 whisperX 指向的日语模型不存在？但我觉得大概率是网络问题？

是网络问题，我看日志说会检测镜像站，但whisperx-align模型自动下载还是选择了官方源；我同时手动去镜像站下载了本地模型，但是不清楚放在哪个路径下进行加载

**Comment by Huanshere** [comment]
这个 align 的 model 似乎是放在安装的环境里的，可能比较难手动放置。所以唯一的办法只能解决网络问题了～
