### ISSUE TITLE
什么时候开发个API接口 来使用，实现自动化

### ISSUE THREAD

**Issue by joe12801** [Huanshere/VideoLingo#283]
什么时候开发个API接口 来使用，实现自动化

**Comment by Huanshere** [comment]
嗯我在考虑将现有的 batch 模式改为 api 模式，但是鉴于中间涉及环节较多，有小概率出错，不确定 api 是否能够稳定运行

**Comment by Huanshere** [comment]
现在已经非常稳定了，有需要的可以自行开发 api，商业版也会开放 api 接口，开源版暂时没有开发 api 的计划。
