### ISSUE TITLE
运行报错：ImportError: cannot import name 'load_config' from 'core.config_utils'

### ISSUE THREAD

**Issue by gaspire** [Huanshere/VideoLingo#286]
运行报错：ImportError: cannot import name 'load_config' from 'core.config_utils'
File "/core/translate_once.py", line 9, in <module>
    from core.config_utils import load_config

**Comment by Huanshere** [comment]
😂下午提交代码脑抽了 cursor 写了个 bug，已经修复 3660b0e 抱歉～
