### ISSUE TITLE
intel mac 执行“Translate and Generate Subtitles“模块失败闪退问题

### ISSUE THREAD

**Issue by minkoIsReady** [Huanshere/VideoLingo#287]
翻译模块无法执行诶，请教一下要怎么跑呀。视频下载，网页端播放都是正常的。
报错Terminal截图：<img width="1774" alt="截屏2024-11-27 00 07 27" src="https://github.com/user-attachments/assets/fac3c98b-6e89-40ec-8df8-add6428a4125">
➡️🎵 Converting to high quality audio with FFmpeg ......
🎬➡️🎵 Converted <output/Amazon⧸AWS S3 (Simple Storage Service) Basics ｜ S3 Tutorial, Creating a Bucket ｜ AWS for Beginners.webm> to <output/audio/raw.mp3> with FFmpeg

🗜️ Converting to low quality audio with FFmpeg ......
🗜️ Converted <output/audio/raw.mp3> to <output/audio/for_whisper.mp3> with FFmpeg
🔪 Starting audio segmentation...
🔪 Audio split into 1 segments
🔍 Checking HuggingFace mirrors...
✓ Official: 0.04s
✓ Mirror: 0.04s
🚀 Selected mirror: https://hf-mirror.com (0.04s)
🚀 Starting WhisperX using device: cpu ...
📦 Batch size: 1, ⚙️ Compute type: int8
▶️ Starting WhisperX for segment 0.00s to 591.48s...
📥 Using WHISPER model from HuggingFace: large-v3 ...
**You can ignore warning of `Model was trained with torch 1.10.0+cu102, yours is 2.0.0+cu118...`**
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../../.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.2. Bad things might happen unless you revert torch to 1.x.
note: You will see Progress if working correctly
[1]    80299 segmentation fault  streamlit run st.py
/opt/anaconda3/envs/videolingo/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

使用的conda env 依赖：[dependences.txt](https://github.com/user-attachments/files/17922346/dependences.txt)
运行配置：Chrome v131.0.6778.86（x86_64）；Macos 15.1；qwen2.5 72b-instruct

**Comment by Huanshere** [comment]
这是转录过程出错的，报错似乎显示的是内存不足，cpu 上跑可能需要 16g 内存
