### ISSUE TITLE
最后一步配音gpt-sovits-v2 api调用失败

### ISSUE THREAD

**Issue by JohnZero2023** [Huanshere/VideoLingo#297]
![a1](https://github.com/user-attachments/assets/09e95e3b-4ddb-4962-812b-e6ab23f85075)
按照教程配置，gpt-sovits自训练模型，yaml和语音文件已重命名放入configs目录下。运行最后一步配音调用404错误，请教大佬如何解决

**Comment by Huanshere** [comment]
一开始报两三个 404 是正常现象，不太清楚为什么，等三十秒应该就正常运行了

**Comment by Huanshere** [comment]
其他用户是可以正常使用的，应该没问题
