### ISSUE TITLE
windows一键安装完成后，再次启动bat报错显示No module named streamlit

### ISSUE THREAD

**Issue by KinoJian** [Huanshere/VideoLingo#298]
windows一键安装完成后，再次启动bat报错显示No module named streamlit，请问这是什么问题呢

![image_42](https://github.com/user-attachments/assets/43ba08d3-b0d5-48cc-a841-0847b38c5ad5)

**Comment by Huanshere** [comment]
第一次能启动吗？可以删掉那个文件夹重新安装，注意看中间步骤有没有红色的报错

**Comment by KinoJian** [comment]
> 第一次能启动吗？可以删掉那个文件夹重新安装，注意看中间步骤有没有红色的报错

删掉重新之后，重新安装完显示的是这个，是没有红色报错的

![image_45](https://github.com/user-attachments/assets/5a35365b-425c-4e80-9ca9-cb5aa226d10f)
![image_47](https://github.com/user-attachments/assets/24fe7474-a360-4644-b75e-5bb9275e6a16)

![image_46](https://github.com/user-attachments/assets/5de33c00-fd57-40de-b833-a5c0d2f30821)

**Comment by Huanshere** [comment]
不好意思，一键安装脚本还是适用性很差，现在回滚回源码安装了，测试过了
