### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by jek6899** [Huanshere/VideoLingo#301]
CUDA 安装好了,一直卡在这
![image](https://github.com/user-attachments/assets/f0a95a2c-1800-4f2a-a499-26df1931b327)

**Comment by Huanshere** [comment]
嗯一键脚本确实不适用于所有电脑，现在回滚回了源码安装～抱歉

**Comment by jek6899** [comment]
源码安装-也是卡在这里.

**Comment by Huanshere** [comment]
参考最新的说明～应该是 cuda 和 cudnn 没有安装导致的
