### ISSUE TITLE
安装依赖冲突

### ISSUE THREAD

**Issue by jek6899** [Huanshere/VideoLingo#304]
Successfully uninstalled whisperx-3.1.1
  DEPRECATION: Legacy editable install of whisperx==3.1.1 from file:///H:/VideoLingo/thirdparty/whisperX (setup.py deve7
  Running setup.py develop for whisperx
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavio.
spacy 3.7.4 requires typer<0.10.0,>=0.3.0, but you have typer 0.14.0 which is incompatible.
weasel 0.3.4 requires typer<0.10.0,>=0.3.0, but you have typer 0.14.0 which is incompatible.
Successfully installed typer-0.14.0 whisperx
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ whisperX 安装完成                                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Installing collected packages: typer
  Attempting uninstall: typer
    Found existing installation: typer 0.14.0
    Uninstalling typer-0.14.0:
      Successfully uninstalled typer-0.14.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavio.
pyannote-database 5.1.0 requires typer>=0.12.1, but you have typer 0.9.4 which is incompatible.
Successfully installed typer-0.9.4

**Comment by lizheng2018CC** [comment]
我也遇到这个问题了。虽然程序能启动，网页能打开，但是网页一直显示running，下面一片空白。我已经把显卡驱动更新到最新，测试环境是ubuntu22.04

**Comment by Huanshere** [comment]
嗯我确实遇到了这个问题，spacy 和 whisperX 的 pyannote 的冲突，之前安装 git 版不会有问题，我尝试 fix 一下。但在我的电脑上不影响使用。感谢反馈

**Comment by Huanshere** [comment]
在 35d9bf7 中已经回滚到 v2.0 的安装方式，现在不会有报错了。 whisperX 和 demucs 都是从 git 安装了，小白用户只能靠自己处理网络环境了 QAQ
