### ISSUE TITLE
OSError: 参考音频在3~10秒范围外，请更换！

### ISSUE THREAD

**Issue by yhqqxq** [Huanshere/VideoLingo#31]
![微信截图_20240830212214](https://github.com/user-attachments/assets/88d1d10b-9fc6-4786-b76d-95bcb0bfec5e)
![微信截图_20240830212225](https://github.com/user-attachments/assets/641f6d2d-6afb-49c6-8716-d6291bf7d66b)

如图所见~
视频长度只有5s，提示不在3~10秒内，这个该怎么处理？

**Comment by Huanshere** [comment]
现在版本的配音有很多要改进的，现在参考音频会跳过第一句话所以会报错哈哈哈

**Comment by yhqqxq** [comment]
期待后续改进
