### ISSUE TITLE
优化代码

### ISSUE THREAD

**Issue by baogeer** [Huanshere/VideoLingo#316]
def get_audio_duration(audio_file: str) -> float:
    # cmd = ['ffmpeg', '-i', audio_file]
    # process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    # _, stderr = process.communicate()
    # ffmpeg_res = stderr.decode('utf-8', errors='ignore')
    # try:
    #     duration_str = [line for line in ffmpeg_res.split('\n') if 'Duration' in line][0]
    #     duration_parts = duration_str.split('Duration: ')[1].split(',')[0].split(':')
    #     duration = float(duration_parts[0]) * 3600 + float(duration_parts[1]) * 60 + float(duration_parts[2])
    # except Exception as e:
    #     print(f"[red]❌ Error: Failed to get audio duration: {e}[/red]")
    #     duration = 0
    audio_clip = AudioFileClip(audio_file)
    duration = audio_clip.duration
    return duration

**Comment by Huanshere** [comment]
以前是这么干的，但是很容易出错，ffmpeg 是兼容性的神
