### ISSUE TITLE
能否使用CrisperWhisper 作为 whsperx 的备选方案

### ISSUE THREAD

**Issue by vanch007** [Huanshere/VideoLingo#319]
https://github.com/nyrahealth/CrisperWhisper
🎯准确的单词级时间戳：通过在训练期间利用调整后的标记器和自定义注意力损失，即使在不流畅和暂停的情况下也能提供精确的时间戳。
📝逐字转录：准确转录每个口语单词，包括并区分“嗯”和“呃”等填充词。
🔍填充物检测：检测并准确转录填充物。
🛡️幻觉缓解：最大限度地减少转录幻觉以提高准确性。

**Comment by vanch007** [comment]
whisperX 不支持 mac 的 mps，在它的项目 issues 中一直未解决

**Comment by Huanshere** [comment]
似乎这个只支持英文？而且没有vad很容易出现幻觉。

**Comment by Huanshere** [comment]
我记得刚出来的时候关注过几天，还有另一个美杜莎也是宣称效果不错，但是星星数量不多，可能反响没那么好

**Comment by vanch007** [comment]
> 似乎这个只支持英文？而且没有vad很容易出现幻觉。

https://github.com/user-attachments/assets/dd986f8c-b2a3-4d62-9235-136a858fad0e

https://github.com/user-attachments/assets/729ff0c8-a9d6-404f-a9d0-a8277d2925b1



测试了支持中文识别，效果我就不知道这么对比了，但是支持苹果 mps 加速

**Comment by Huanshere** [comment]
whisperX 有时候也是 分割到词语。另外我看 crisper 的 issues 里提及了幻觉和空时间轴的问题，似乎表现不够稳定，有很多 whisper 本身的问题。 whisperX 由于是使用了二阶段的 wav2vac 强制对齐，解决了很多不稳定的问题。

> 中文不能分割到单字，会分割到词语
