### ISSUE TITLE
使用dockerfile自己打包镜像后，容器缺少libnvidia-encode.so.1

### ISSUE THREAD

**Issue by fsqinghuayu** [Huanshere/VideoLingo#327]
本地直接运行是可以的，放到docker容器里， ffmpeg报错Cannot load libnvidia-encode.so.1

**Comment by Huanshere** [comment]
GPT 给的解决方案：

这个错误通常是因为系统上缺少NVIDIA的编码库`libnvidia-encode.so.1`。以下是一些可能的解决方案：

1. **安装NVIDIA驱动**：确保你已经安装了最新的NVIDIA驱动。可以通过以下命令检查驱动是否安装：

   ```bash
   nvidia-smi
   ```

   如果没有安装，可以参考NVIDIA的官方文档进行安装。

2. **安装CUDA工具包**：有时候需要安装CUDA工具包来获取编码库。可以通过以下命令安装：

   ```bash
   sudo apt-get install nvidia-cuda-toolkit
   ```

3. **检查环境变量**：确保`LD_LIBRARY_PATH`环境变量中包含了NVIDIA库的路径。可以通过以下命令检查：

   ```bash
   echo $LD_LIBRARY_PATH
   ```

   如果没有包含NVIDIA库路径，可以通过以下命令添加：

   ```bash
   export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
   ```

4. **重启系统**：有时候安装或更新驱动后需要重启系统才能生效。

如果以上方法都无法解决问题，可能需要检查系统的具体配置或者查看FFmpeg和NVIDIA的兼容性问题。

似乎是WSL的问题？

**Comment by Huanshere** [comment]
> 应该是WSL的问题，我把打包好的镜像放到runpod运行就正常了。不过我又发现一个新的问题，我调用from core.step2_whisperX import transcribe这个方法去转录[https://www.youtube.com/watch?v=wUX7HfulJPI，15秒到36秒的内容会丢失（开启了demucs），不开启的情况下音频后半截的内容转录之后大部分的内容都丢失了。都是用代码里的模型没进行任何修改](https://www.youtube.com/watch?v=wUX7HfulJPI%EF%BC%8C15%E7%A7%92%E5%88%B036%E7%A7%92%E7%9A%84%E5%86%85%E5%AE%B9%E4%BC%9A%E4%B8%A2%E5%A4%B1%EF%BC%88%E5%BC%80%E5%90%AF%E4%BA%86demucs%EF%BC%89%EF%BC%8C%E4%B8%8D%E5%BC%80%E5%90%AF%E7%9A%84%E6%83%85%E5%86%B5%E4%B8%8B%E9%9F%B3%E9%A2%91%E5%90%8E%E5%8D%8A%E6%88%AA%E7%9A%84%E5%86%85%E5%AE%B9%E8%BD%AC%E5%BD%95%E4%B9%8B%E5%90%8E%E5%A4%A7%E9%83%A8%E5%88%86%E7%9A%84%E5%86%85%E5%AE%B9%E9%83%BD%E4%B8%A2%E5%A4%B1%E4%BA%86%E3%80%82%E9%83%BD%E6%98%AF%E7%94%A8%E4%BB%A3%E7%A0%81%E9%87%8C%E7%9A%84%E6%A8%A1%E5%9E%8B%E6%B2%A1%E8%BF%9B%E8%A1%8C%E4%BB%BB%E4%BD%95%E4%BF%AE%E6%94%B9)

不开启的话容易遇到 whisper 的幻觉问题，开启的话有时候会因为声音分离过多而导致人声变小，损失一些内容。还和运行的机器有关。
