### ISSUE TITLE
model "Ollama" not found

### ISSUE THREAD

**Issue by lynhao** [Huanshere/VideoLingo#331]
请问，我用了Ollama模型后，在点击start processing subtitles时候抛异常了，也对照着api文档把里面说的修改了，麻烦帮忙看看是哪里出问题了~
<img width="854" alt="截屏2024-12-08 17 29 26" src="https://github.com/user-attachments/assets/1fc66a06-2ca8-428e-90ab-478af0c097a5">
<img width="558" alt="截屏2024-12-08 17 37 33" src="https://github.com/user-attachments/assets/62a28ea1-24c2-436c-b628-0e72ab13f7ee">
<img width="645" alt="截屏2024-12-08 17 37 59" src="https://github.com/user-attachments/assets/fdfd743d-7585-47ef-8aec-147bf85f4565">
<img width="448" alt="截屏2024-12-08 17 38 15" src="https://github.com/user-attachments/assets/2c4075bc-1ead-4b3c-a698-4599bf546dba">

**Comment by Huanshere** [comment]
model 处应该填写的是你运行的模型，而不是 Ollama~
