### ISSUE TITLE
运行后报BadZipFile: File is not a zip file错误

### ISSUE THREAD

**Issue by draculakkk** [Huanshere/VideoLingo#334]
按照使用文档的步骤安装，完成之后运行报BadZipFile: File is not a zip file错误，操作系统win11，N卡，python 3.10和最新版本试过都一样
![2024-12-12_232252](https://github.com/user-attachments/assets/f7a1c62d-ab1d-4d20-9cd7-539a8f20bb11)

**Comment by draculakkk** [comment]
最后我手动下载cmudict.zip包到C:\nltk_data\corpora，设置了个环境变量就好了

**Comment by Huanshere** [comment]
是的，这些时候是网络问题～ 挺闹人的😣

**Comment by telanxu** [comment]
缺少的文件都在这里可以找到下载链接。。。。
https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml
