### ISSUE TITLE
使用 OpenAI API 的时候经常出现Rate limit reached错误

### ISSUE THREAD

**Issue by neohob** [Huanshere/VideoLingo#34]
Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-3vHNf8JxesfafaW5WNqB on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}

**Comment by Huanshere** [comment]
现在是 8 线程访问，可以在 core step4_2 translate_all 42 行改“max_workers=8”

**Comment by neohob** [comment]
改成 1 了还会出错，另外在字幕对齐步骤也会出现下面错误：

发生未预期的错误: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-3vHNf8JxesfafaW5WNqB on tokens per min (TPM): Limit 10000, Used 9524, Requested 497. Please try again in 125ms. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
正在重试...

**Comment by Huanshere** [comment]
这是 api 的问题，检查用的 api 提供商的并发数量限制

**Comment by neohob** [comment]
我直接用的 api.openai.com 这个api

**Comment by Huanshere** [comment]
看起来是因为这 key 个没有付费 所以并发数量有些限制

**Comment by neohob** [comment]
现在 openai 是预付费机制，我昨天刚充了值，当然最后错误好多次一直重试后还是成功了，就是很多次错误

**Comment by Huanshere** [comment]
嗯就是因为多线程访问触发了访问限制了
