### ISSUE TITLE
请教一下报错：目前Linux下合并中文字幕展示乱码

### ISSUE THREAD

**Issue by UFOyyds** [Huanshere/VideoLingo#35]
![image](https://github.com/user-attachments/assets/27d61c59-e206-4483-ab73-cefbcd2b1a49)
请教一下大佬，感谢！为何我每次生成完成后都会显示：“目前 Linux 下合并中文字幕展示乱码，请下载 srt 文件自行压制处理～” 
于是我就去剪映里去合并去了。

**Comment by Huanshere** [comment]
嗯 linux 下的 ffmpeg 合成中文字幕我还没搞懂为什么出错。。。还是建议自己用剪映压制，这样字幕样式能控制更好看一些

**Comment by UFOyyds** [comment]
> 嗯 linux 下的 ffmpeg 合成中文字幕我还没搞懂为什么出错。。。还是建议自己用剪映压制，这样字幕样式能控制更好看一些

好的谢谢大佬，但我的是Windows系统，不是linux

**Comment by Huanshere** [comment]
哦？你是windows Arm吗？

**Comment by UFOyyds** [comment]
> 哦？你是windows Arm吗？

我是win11

**Comment by Huanshere** [comment]
什么cpu芯片
