### ISSUE TITLE
无效的令牌？ 这个怎么处理？

### ISSUE THREAD

**Issue by helinyu** [Huanshere/VideoLingo#36]
Exception: 在3次尝试后仍然失败: Error code: 401 - {'error': {'message': '无效的令牌 (request id: 20240903132633756782166AeCxdlyd)', 'type': 'yunwu_api_error'}}

**Comment by airhao3** [comment]
这说明你的token可能写错了， 或者是api做了限制了呢， 在或者是你请求频繁被限制了。我之前是遇到过这种情况， 加代理就可以用了。

**Comment by Huanshere** [comment]
之前在 streamlit web 页面修改了 api 后需要重启整个 streamlit。刚刚更新了，现在可以在 web 端修改后直接点击验证使用，不需要重启。

另外，如果还是遇到 apierror 可以尝试更换 base url
