### ISSUE TITLE
最后配音的部分总是让我检查 output/audio/sovits_tasks.xlsx 中的对应内容并修改

### ISSUE THREAD

**Issue by neohob** [Huanshere/VideoLingo#37]
<img width="1598" alt="image" src="https://github.com/user-attachments/assets/69899949-f4a6-4874-a0ef-e002c243d781">

不知道能怎么改会改好

**Comment by helinyu** [comment]
删掉，重新生成吧

**Comment by Huanshere** [comment]
新的配音版本在做，稍等～

**Comment by neohob** [comment]
期待

另外会不会解决，配音声音重叠的问题？字幕和语音时间轴有重叠导致语音也重叠

有个小 bug，例如，写了翻译成法文，日文，output 目录字幕文件还是以_en 命名

**Comment by Huanshere** [comment]
命名的 bug v0.3 修了应该～ 声音重叠的问题似乎 whisper 的 api 不会有这个现象？

**Comment by neohob** [comment]
谢谢，多线程数量是否可以在界面上修改调整？

**Comment by Huanshere** [comment]
可以在 config 里手动改，现在基本只推荐云雾 api，所以应该不太需要改？

**Comment by neohob** [comment]
最好不要改 config，每次更新代码都比较麻烦，git pull 有冲突，另问下重写的配音功能什么时候会有，期待

**Comment by Huanshere** [comment]
嗯现在采用了config.example.py了，后面考虑把apikey单独放在一个设置文件里。

目前版本正在优化whisper timestamped的识别，这个是这个项目的根基，打算把它做得更精细和完美，这样才能保证配音不出错。
