### ISSUE TITLE
使用 yt-dlp 从 Youtube 链接下载视频这个功能在哪里

### ISSUE THREAD

**Issue by wick233** [Huanshere/VideoLingo#49]
部署完之后没有看到用yt-dlp下载视频的地方，只有上传视频
![image](https://github.com/user-attachments/assets/293446cd-09ad-4dc9-9d8f-d654fe27b213)

**Comment by Huanshere** [comment]
哦之前写的部署在 linux 上就把那个下载隐藏，因为部署在境内的云上，我看看咋改改

**Comment by Huanshere** [comment]
在 819837c 中修复了~感谢反馈

**Comment by wick233** [comment]
> 在 [819837c](https://github.com/Huanshere/VideoLingo/commit/819837cdfd3a725173e7708871ce2ebc35ec9fd0) 中修复了~感谢反馈

我上传了个视频然后点开始按钮，等了几十分钟之后报错了
![IMG_20240919_172917](https://github.com/user-attachments/assets/76511da6-bc3f-4031-bfd9-3070890f4c59)

**Comment by Huanshere** [comment]
linux 系统是吗，是用的 whisperX 模型吗
