### ISSUE TITLE
上传完视频点开始按钮过了几十分钟之后报错connection error 504

### ISSUE THREAD

**Issue by wick233** [Huanshere/VideoLingo#50]
Connection error
Connection failed with status 504, and response " <html><head> <meta type="copyright" content="Copyright (C) 1996-2018 The Squid Software Foundation and contributors"> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> <title>错误: 不能获取请求的 URL</title> <style type="text/css"></style> </head><body id="ERR_CONNECT_FAIL"> <div id="titles"> <h1>错误</h1> <h2>您所请求的网址（URL）无法获取</h2> </div> <hr> <div id="content"> <p>当尝试取回该 URL 时遇到下面的错误：<a href="http://64.69.41.28:8501/_stcore/health">http://64.69.41.28:8501/_stcore/health</a></p> <blockquote id="error"> <p><b>连接到 64.69.41.28 失败。</b></p> </blockquote> <p id="sysmsg">系统返回以下内容：<i>(111) Connection refused</i></p> <p>The remote host or network may be down. Please try the request again.</p> <p>缓存服务器的管理员 <a href="mailto:cncs-netapp@foxconn.com?subject=CacheErrorInfo%20-%20ERR_CONNECT_FAIL&amp;body=CacheHost%3A%20TPEproxyNwing%0D%0AErrPage%3A%20ERR_CONNECT_FAIL%0D%0AErr%3A%20(111)%20Connection%20refused%0D%0ATimeStamp%3A%20Thu,%2019%20Sep%202024%2009%3A07%3A27%20GMT%0D%0A%0D%0AClientIP%3A%2010.199.149.7%0D%0AServerIP%3A%2064.69.41.28%0D%0A%0D%0AHTTP%20Request%3A%0D%0AGET%20%2F_stcore%2Fhealth%20HTTP%2F1.1%0AProxy-Connection%3A%20keep-alive%0D%0AProxy-Authorization%3A%20Basic%20RjEyMTYxOTc6ZWlsZWVuMTk4Nio%3D%0D%0AAccept%3A%20application%2Fjson,%20text%2Fplain,%20*%2F*%0D%0AUser-Agent%3A%20Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML,%20like%20Gecko)%20Chrome%2F128.0.0.0%20Safari%2F537.36%0D%0AReferer%3A%20http%3A%2F%2F64.69.41.28%3A8501%2F%0D%0AAccept-Encoding%3A%20gzip,%20deflate%0D%0AAccept-Language%3A%20zh-CN,zh%3Bq%3D0.9%0D%0ACookie%3A%20zfile-token%3D0eec88d0-64dd-4fff-81d5-9f4a1ad4f260%3B%20cloudreve-session%3DMTcyNjIwNzc3M3xOd3dBTkVKYVFsQlRXa0pLV2tkV1NGbFNVMHhKTlZwVFZsWldORE5TV0VwSFdFUXpTVkpHTWxZMlNWQmFXRWhRVjFkVVVUTkVXRUU9fPUeUS5TUbrIMD5CQVVoxizEuMXv1M_tnMGase1ZZ6zI%3B%20_xsrf%3D2%7Cfae8be54%7Cda8925dd3cd7edf65bca72634c2a0792%7C1726728275%3B%20ajs_anonymous_id%3D867f8778-2d1f-4918-8bd9-51a51257987f%0D%0AHost%3A%2064.69.41.28%3A8501%0D%0A%0D%0A%0D%0A">cncs-netapp@foxconn.com</a>.</p> <br> </div> <hr> <div id="footer"> <p>已由 TPEproxyNwing (squid/3.5.28) 生成 Thu, 19 Sep 2024 09:07:27 GMT</p>  </div> </body></html> ".

**Comment by wick233** [comment]
又试了几次报错没有找到模块
ModuleNotFoundError: No module named 'whisperx'
Traceback:
File "/opt/conda/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
File "/opt/conda/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
File "/app/st.py", line 123, in <module>
    main()
File "/app/st.py", line 117, in main
    text_processing_section()
File "/app/st.py", line 32, in text_processing_section
    process_text()
File "/app/st.py", line 51, in process_text
    step2_whisper.transcribe(video_file)
File "/app/core/step2_whisper.py", line 17, in transcribe
    from core.all_whisper_methods.whisperX import transcribe as ts
File "/app/core/all_whisper_methods/whisperX.py", line 3, in <module>
    import whisperx

**Comment by Huanshere** [comment]
是挂在了linux服务器上吗？这个看起来是文件下载回传的网络问题，可能是网络原因也可能是streamlit的原因

**Comment by wick233** [comment]
> 原因也可能是streamlit的原因

用docker部署到了linux上，切换Whisper Method还是会报找不到模块错误，用的是cc洛杉矶的小鸡

**Comment by Huanshere** [comment]
No module named 'whisperx' 是因为没有安装 third party 文件夹里面的 whisperX 项目，docker 稳定性未知，最好参照本地部署指南进行命令行安装。另外，Linux 部署非 whisper api 版没有测试过，理论上应该没问题～

**Comment by Huanshere** [comment]
还是推荐使用一键整合包哈哈哈

**Comment by Huanshere** [comment]
似乎远程传文件容易导致这个问题，这似乎是 streamlit 处理大文件时的弊端，默认上传文件的大小限制在 200M，是我手动改大了，因此还是建议本地上传，或者部署后用链接下载的方式。
