### ISSUE TITLE
【考虑加入唇形同步】

### ISSUE THREAD

**Issue by Huanshere** [Huanshere/VideoLingo#59]
https://github.com/user-attachments/assets/0c954393-0ed8-4587-ba58-a0ca1d85b56b

https://github.com/user-attachments/assets/beeef63a-329a-4e31-ad14-53e5030f6a93

MuseTalk的唇形同步似乎不错，可以考虑以后加入

**Comment by colin4k** [comment]
+1

**Comment by Huanshere** [comment]
问题记录：replicate 有 api 但是在遇到无人脸片段会报错，因此只能考虑本地部署，对显存要求 10G，需要修改源代码下模型，官方似乎已经停止更新
