### ISSUE TITLE
Youtube视频下载并没有使用最高画质进行下载

### ISSUE THREAD

**Issue by 1PercentSync** [Huanshere/VideoLingo#60]
比如说https://www.youtube.com/watch?v=gj7S4PVK85A
下载下来是1080p的

**Comment by 1PercentSync** [comment]
另外如果能顺带下载封面，对于需要转载的视频会非常有帮助

**Comment by Huanshere** [comment]
确实 后面会把下载视频的分辨率作为选项设置，谢谢建议

**Comment by Huanshere** [comment]
ffe8941 现在可以选择分辨率了！
