### ISSUE TITLE
希望可以加入预定义的词典，在自动生成词典的基础上

### ISSUE THREAD

**Issue by 1PercentSync** [Huanshere/VideoLingo#63]
目前基于项目的自动生成词典可以手动编辑。然而有些专有名词需要在多个视频中固定，拥有一个
类似：
https://github.com/xd2333/GalTransl?tab=readme-ov-file#galtransl%E6%A0%B8%E5%BF%83%E5%8A%9F%E8%83%BD%E4%BB%8B%E7%BB%8D
这样的手动词典可以减少重复工作
更进一步，如果能从自动生成的词典中，从界面把自动生成的词典更正并加入持久化词典就更好了

**Comment by Huanshere** [comment]
有道理，你觉得什么样的格式比较好呢？在根目录下的 `terminology.xlsx` 如何，或是写在 `config.py` 里以字典 GLOBAL_TERMINOLOGY 的方式比较好？

我个人偏向后者，前者虽然更方便但是会让文件目录变复杂，后者作为高级设置放在config中更符合逻辑。

**Comment by 1PercentSync** [comment]
> 有道理，你觉得什么样的格式比较好呢？在根目录下的 `terminology.xlsx` 如何，或是写在 `config.py` 里以字典 GLOBAL_TERMINOLOGY 的方式比较好？
> 
> 我个人偏向后者，前者虽然更方便但是会让文件目录变复杂，后者作为高级设置放在config中更符合逻辑。

个人偏向于不依赖xlsx，如果能在程序范围内取消掉对于xlsx能让使用者不用下载office会有好处，尤其是如果有可能出现需要用户手动编辑文件的情况，我是临时下的office，对于其他人也会有订阅的花费
如果用csv或者json或者自定义个文本然后用tab和换行分隔也好像还不错，最差情况下能用vs code打开。
另外采用工作区/项目的机制个人认为也挺好，这样程序的执行文件和媒体文件/临时中间生成的断句，翻译缓存能分离开来，如果需要提交整个项目给你debug也可以轻松知道需要给你什么，同时对于不同类型的视频可以尤其单独设置。可以有一个全局的设置还有项目的设置
在这之前我是用galtransl改一些prompt来做字幕翻译，他是用于翻译游戏文本的，和这个有一定的相通之处，我觉得存在一些可以参考的地方

**Comment by 1PercentSync** [comment]
> 有道理，你觉得什么样的格式比较好呢？在根目录下的 `terminology.xlsx` 如何，或是写在 `config.py` 里以字典 GLOBAL_TERMINOLOGY 的方式比较好？
> 
> 我个人偏向后者，前者虽然更方便但是会让文件目录变复杂，后者作为高级设置放在config中更符合逻辑。

另外欢迎来玩
https://t.me/+QMDKZyO9GV1kNDA1
这是sakurallm的群，sakurallm是一个专注于日翻中（主要是游戏和小说，包括nsfw内容）的模型
galtransl是其衍生工具之一，我们还有https://github.com/FishHawk/auto-novel
neavo/KeywordGacha，还有我的sakura-share等项目以及不少的微调模型作者

**Comment by Huanshere** [comment]
方法2现在可以在config中设置，在翻译前 pause 让用户自己更新json术语表~
