### ISSUE TITLE
参考音频在3~10秒范围外，请更换！

### ISSUE THREAD

**Issue by colin4k** [Huanshere/VideoLingo#64]
GPT_SoVITS的报错，可能需要在本项目增加相关的判断，我目前是直接在GPT_SoVITS里面注释了相关的限制

**Comment by colin4k** [comment]
> 这似乎是很老的版本的报错了哈哈哈，请问你下载的是哪个版本的代码

最新的 GPT_SoVITS 啊

**Comment by colin4k** [comment]
> 这似乎是很老的版本的报错了哈哈哈，请问你下载的是哪个版本的代码

特意去它的仓库看了下，最新的代码就是这样的：
<img width="973" alt="截屏2024-09-24 19 12 51" src="https://github.com/user-attachments/assets/7eaa01b4-8536-4500-84c6-d3fbcb03e092">

**Comment by Huanshere** [comment]
似乎是你的参考音频的问题~我很久没有复现这个错误了，先关闭这个issue了
