### ISSUE TITLE
加入自选字幕文件然后进行翻译

### ISSUE THREAD

**Issue by 20XIJI** [Huanshere/VideoLingo#66]
有一个Distil版本的whisper,识别英语的速度快特别多,希望可以自己识别字幕后在这里提交进行翻译

**Comment by Huanshere** [comment]
本项目需使用单词级的字幕，才能对长句进行切割，大部分whisper项目做的都是句级的时间轴，试想一下如果有一个两行的句子字幕，在中间切一刀，那么分别的时间轴要如何对齐呢？

基于此，把开源领域的所有项目都测试了一遍，包括whisper本身的word timestamp，whisper_timstamped项目，whisperX项目，最终还是选择了whisperX，比其他项目都稳定得多。
