### ISSUE TITLE
ModuleNotFoundError: No module named 'yt_dlp'  已经手动安装了yt_dl 仍然提示找不到..

### ISSUE THREAD

**Issue by 487306** [Huanshere/VideoLingo#7]
![Snipaste_2024-08-22_06-32-29](https://github.com/user-attachments/assets/deaf5486-c6a9-4c18-86bf-8ff961e4f3f5)
![Snipaste_2024-08-22_06-33-09](https://github.com/user-attachments/assets/851315bf-77c2-4e50-8f19-9b922f6ab229)
![Snipaste_2024-08-22_06-37-14](https://github.com/user-attachments/assets/4921c276-cea4-4ee4-8049-dc76f04fad0c)

**Comment by Huanshere** [comment]
似乎以前我也遇到类似的问题... 和系统路径有关系，试试把该环境添加到系统路径中～
