### ISSUE TITLE
重构为web应用，便于无算力资源的小伙伴进行调用

### ISSUE THREAD

**Issue by huguanjin** [Huanshere/VideoLingo#71]

**Comment by huguanjin** [comment]
1.后端框架--FastApi；
2.前端框架--Vue.js

**Comment by Huanshere** [comment]
正在考虑商业化，在此之前还有一些功能需要开发完善，还有最后几个影响稳定性的 bug 需要修一修，谢谢关注和建议～

**Comment by Huanshere** [comment]
已经添加了 colab 版本~ 202a526

**Comment by yangwenmai** [comment]
等你的商业化版本出来之后，我第一时间试用。

**Comment by Huanshere** [comment]
感谢 目前考虑的定价是 2r/min，在做市场调研～有什么好的建议和想法吗？
