### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by laosuan** [Huanshere/VideoLingo#72]
{
        "model": "anthropic/claude-3.5-sonnet",
        "prompt": "\n### Role\nYou are a professional subtitle editor, editing and optimizing lengthy subtitles that exceed voiceover time before handing them to voice actors. Your expertise lies in cleverly shortening subtitles slightly while ensuring the original meaning and structure remain unchanged.\n\n### Subtitle Data\n<subtitles>\nSubtitle: \"是霍华德·加德纳的《五种心智》（Five Frames of Mind）。\"\nDuration: 3.2249999999999943 seconds\n</subtitles>\n\n### Processing Rules\nConsider a. Reducing filler words without modifying meaningful content. b. Omitting unnecessary modifiers or pronouns, for example:\n    - \"Please explain your thought process\" can be shortened to \"Please explain thought process\"\n    - \"We need to carefully analyze this complex problem\" can be shortened to \"We need to analyze this problem\"\n    - \"Let's discuss the various different perspectives on this topic\" can be shortened to \"Let's discuss different perspectives on this topic\"\n    - \"Can you describe in detail your experience from yesterday\" can be shortened to \"Can you describe yesterday's experience\" \n\n### Processing Steps\nPlease follow these steps and provide the results in the JSON output:\n1. Analysis: Briefly analyze the subtitle's structure, key information, and filler words that can be omitted.\n2. Trimming: Based on the rules and analysis, optimize the subtitle by making it more concise according to the processing rules.\n\n### Output Format\nPlease complete the following JSON data, where << >> represents content you need to fill in:\n{\n    \"analysis\": \"<<Brief analysis of the subtitle, including structure, key information, and potential processing locations>>\",\n    \"trans_text_processed\": \"<<Optimized and shortened subtitle in the original subtitle language>>\"\n}\n",
        "response": "",
        "message": null
    }
    
    
    cause error:
    
    VideoLingo/core/step8_gen_audio_task.py", line 57, in check_len_then_trim
    shortened_text = response['trans_text_processed']
TypeError: string indices must be integers

建议加上重试机制,检查返回的内容后再存到文件中;

**Comment by Huanshere** [comment]
感谢建议 已补充 0e5c181 稍后merge到main中
