### ISSUE TITLE
翻译出来的中文有时候会出现乱码

### ISSUE THREAD

**Issue by zoujack018** [Huanshere/VideoLingo#75]
翻译出来的中文有时候会出现乱码
节选：
│ Source Line │ where it contracts driving out to some 4,400 small delivery businesses that employ 390,000 drivers. │
│ Target Line │ 该计划外包配送业务给约4400家小企业，共雇佣39万名司机。  

                                   🔗 Aligned parts
┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Language    ┃ Parts                                                                 ┃
┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ SRC_LANG    │ where it contracts driving out                                        │
│             │  to some 4,400 small delivery businesses that employ 390,000 drivers. │
│ TARGET_LANG │ 该计划外包配送业务                                                    │
**│             │ 给约4400家   企业，共雇佣39万名司机。                                 │**

![image](https://github.com/user-attachments/assets/7ab814b7-3624-46a0-a51d-971e750ebaca)

**Comment by Huanshere** [comment]
神奇的错误，请问是什么系统呢，应该是编码的某些冲突的问题

**Comment by zoujack018** [comment]
系统是windows11，模型用4o和sonnet3.5都出现了这个问题。

**Comment by Huanshere** [comment]
不太清楚，没有复现过，可能是和系统编码有关。

**Comment by Huanshere** [comment]
暂时没有人复现~
