### ISSUE TITLE
Replicate API error

### ISSUE THREAD

**Issue by seramat** [Huanshere/VideoLingo#76]
已经在Replicate设置billing, 还是有这个误码。这是需要翻墙么？哪里设置啊？
谢谢
![CleanShot 2024-09-30 at 12 44 26@2x](https://github.com/user-attachments/assets/c1e094aa-cf1e-4c0e-a43a-53d296d4ac6a)

**Comment by Huanshere** [comment]
国庆节快乐🎉

**Comment by Huanshere** [comment]
可能是上传音频过程出现某种超时导致？我看某些群友也反馈这个问题，我没有复现过这个问题，可能是梯子的原因

**Comment by Huanshere** [comment]
啊哈哈哈找到问题了，是因为之前送去的音频太大了没有压缩导致的，在02747f3已经修复~试试新版本吧
