### ISSUE TITLE
能否支持本地的语言模型？

### ISSUE THREAD

**Issue by Datou** [Huanshere/VideoLingo#77]
比如qwen2

**Comment by Huanshere** [comment]
本项目处理的比较精细，prompt的思维链和格式要求比较多，所以较小的模型容易出错，Qwen2.5 72B勉强可以~

**Comment by Datou** [comment]
> 本项目处理的比较精细，prompt的思维链和格式要求比较多，所以较小的模型容易出错，Qwen2.5 72B勉强可以~

谢谢，原来是这样。72b本地跑不动，32b能跑。如果能微调一个专用的本地模型就好了，希望以后有小模型能胜任这个工作。

**Comment by Huanshere** [comment]
确实！AI的进化会特别快的！

话说回来，我认为本地模型除了隐私没有别的优势，deepseekv2.5和Qwen2.5 72B都做到 ￥2/1M tokens的价格了，而且支持并发还很稳定~

**Comment by Datou** [comment]
> 确实！AI的进化会特别快的！
> 
> 话说回来，我认为本地模型除了隐私没有别的优势，deepseekv2.5和Qwen2.5 72B都做到 ￥2/1M tokens的价格了，而且支持并发还很稳定~

本地模型除了隐私还有个开源优势，有机会自己微调，api后面的模型只能用，它说不能干啥就不能干啥。

**Comment by Huanshere** [comment]
确实！以后如果商业化了收集到足够的数据也是想自己微调模型的，这样风格也方便控制！
