### ISSUE TITLE
能否在google colab上安装？

### ISSUE THREAD

**Issue by sijitang** [Huanshere/VideoLingo#82]
请问有人能否在google colab上安装过吗？应该如何设置，比如一键安装，

**Comment by Huanshere** [comment]
理论上按照安装步骤进行即可，在 install.py 中考虑了 linux 的情况，一个月前在 Linux 上部署过，已经许久没有测试过，如果你能测试一下并提供反馈我很乐意帮忙 debug 解决～

**Comment by Huanshere** [comment]
https://x.com/huangyun_122/status/1841054092149272878?s=46

似乎是能正常在 colab 上运行！

**Comment by joeaki1983** [comment]
这种问题问ChatGPT就行了，它会一步一步教你

**Comment by Huanshere** [comment]
会尽快出一个 colab 一键部署

**Comment by sijitang** [comment]
是可以部署成功，但google colab运行Streamlit，提供的URL是 Colab 虚拟机内部的，貌似要建一个Tunnel连接到本地主机才能在本地打开。有什么别的办法吗？
 All installation steps are completed! │
╰───────────────────────────────────────╯
Please use the following command to start Streamlit:
streamlit run st.py

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501/
  Network URL: http://172.28.0.12:8501/
  External URL: http://34.106.251.163:8501/

**Comment by Huanshere** [comment]
1. uvr5 就是个调用各种的框架，实际上就是调用了两个类似 demucs 的 pth，代码引用的 gpt-sovits 的
2. 是的，所以样式很难更好看了 QAQ，以后商业版在考虑换一些 react 弄好看字幕的

**Comment by Huanshere** [comment]
2h 之前已经有官方的 colab 啦，使用的是 ngrok 的方式，注册获取免费 token 就能用 !
