### ISSUE TITLE
能否加个省时的feat:  上传mp3，导出srt

### ISSUE THREAD

**Issue by eefeng** [Huanshere/VideoLingo#87]

**Comment by Huanshere** [comment]
视频抽取 mp3 就 2s🫣

**Comment by Huanshere** [comment]
“比如有一个外文srt, 只需要输出中文或者双语的srt”这个做不到，本项目使用的是单词级别的字幕，思考一个问题：如果出现了双行的外文，需要切割开，那么新的时间轴是什么呢？中间断开部分的时间戳是什么呢？

另外～字幕压制到视频的过程是可选的，在“压制视频分辨率”可以选择不压制。

搬运愉快~

**Comment by eefeng** [comment]
> “比如有一个外文srt, 只需要输出中文或者双语的srt”这个做不到，本项目使用的是单词级别的字幕，思考一个问题：如果出现了双行的外文，需要切割开，那么新的时间轴是什么呢？中间断开部分的时间戳是什么呢？
> 
> 另外～字幕压制到视频的过程是可选的，在“压制视频分辨率”可以选择不压制。
> 
> 搬运愉快~

手动提供output中的src_subtitles.srt ，是不是就不用处理转录的步骤

**Comment by eefeng** [comment]
> “比如有一个外文srt, 只需要输出中文或者双语的srt”这个做不到，本项目使用的是单词级别的字幕，思考一个问题：如果出现了双行的外文，需要切割开，那么新的时间轴是什么呢？中间断开部分的时间戳是什么呢？
> 
> 另外～字幕压制到视频的过程是可选的，在“压制视频分辨率”可以选择不压制。
> 
> 搬运愉快~

1. 使用 WhisperX 单词级转录
2. 使用 NLP 和 LLM 分割句子
3. 总结提取术语和多步翻译
4. 二次切割长字幕并对齐
5. 生成时间轴和字幕

一个视频已经有en版本的srt了，步骤一是不必要的吧

**Comment by Huanshere** [comment]
考虑到会增加代码复杂性，且功能较小众，暂时不考虑支持mp3输入，如有需求可以手动转化为mp4输入。

另外，单独翻译srt的功能正在施工~
