### ISSUE TITLE
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by leavenotrace** [Huanshere/VideoLingo#9]
run: streamlit run st.py 
<img width="1054" alt="image" src="https://github.com/user-attachments/assets/0d28210a-d85c-4155-b1e8-6201e741e2de">

**Comment by XGCoder** [comment]
win11    出现这个问题  把 requirements.txt  中  numpy版本固定一下就好了    numpy==1.26.4

**Comment by leavenotrace** [comment]
不是win11，是macOS 15

**Comment by XGCoder** [comment]
> 不是win11，是macOS 15

我说我是win11，  出现这样的问题通过固定numpy版本的方式处理好了  你可以在mac端试下

**Comment by Huanshere** [comment]
更新了 requirements.txt 把numpy固定为1.26.4，应该能解决～ 期待反馈 @Huanshere 6a01154
