### ISSUE TITLE
进程异常结束

### ISSUE THREAD

**Issue by SomeoneKong** [Huanshere/VideoLingo#93]
有的时候会遇到在 split阶段进程直接退出了
我自己使用spacy的时候也时常遇到core导致python进程结束的问题。

建议分离spacy相关的任务到一个单独的python进程，确保主进程不会挂。

以及目前好像即使split结果有的时候，也会重新跑split，建议增加结果已存在的检测。

**Comment by Huanshere** [comment]
<img width="706" alt="image" src="https://github.com/user-attachments/assets/774976c3-fb07-47e7-b182-c2c7fa53f4e2">
1.4 版本开始应该就不会重新跑 split 了。

“在 split阶段进程直接退出了” 是什么原因导致的呢，我还没有复现过，重试一遍能解决吗

**Comment by SomeoneKong** [comment]
重试可以解决，有偶发性，我这是win11系统。
但有的时候连续出现，总是手工重启还有点烦

**Comment by Huanshere** [comment]
感谢反馈，我再看看有没有其他朋友能复现这个问题～

**Comment by SomeoneKong** [comment]
可能与 spacy 的版本有关，最新的3.8系列需要Numpy 2.0，
我目前换成了 "spacy<3.8" 来测试看是否还有问题。

**Comment by Huanshere** [comment]
哦好～ v1.4.1 固定了环境 你也可以试试重新安装看看～

**Comment by yxc0915** [comment]
1.5.1版本已发，请检查新版本是否会出现同样的问题
