### ISSUE TITLE
希望翻译加入硅基流动的api

### ISSUE THREAD

**Issue by vanch007** [Huanshere/VideoLingo#96]
https://siliconflow.cn/zh-cn/
![image](https://github.com/user-attachments/assets/f6647ef6-e8ec-4985-8499-bb926510d1aa)
qwen2.5-72b应该效果也不差

**Comment by Huanshere** [comment]
确实可以！
（其实硅基流动上新 qwen2.5 那一天本项目就默认使用这个，但是后面发现遵循格式还是有问题，甚至有时候不如 deepseek）

**Comment by Huanshere** [comment]
可以自行更改侧边栏的 baseurl使用硅基流动

**Comment by vanch007** [comment]
已经解决，谢谢

**Comment by vanch007** [comment]
一解决
